Global header
underflip/shredindex-frontend pull request #10
Opened 2020-10-24 05:24 UTC by Krank3n

https://trello.com/c/7vNj8V2v/9-global-header

Added Header Navigation along with Dropdown options.
Added Header Test
Added Header Storybook

2020-12-02 01:28 UTC, jakxnz commented
Same deal for this PR. I'm not sure what code is related here, what is the base commit for these changes? Do they come before or after https://github.com/underflip/shredindex-frontend/pull/11 ?

2020-12-04 19:11 UTC, Krank3n commented
> Same deal for this PR. I'm not sure what code is related here, what is the base commit for these changes? And do they come before or after #11 ?

Hey man, this will now be based off cypress dependencies. So it should be clearly just Header changes

2021-01-16 05:50 UTC, jakxnz requested changes
Looking mostly good. I can see placeholder content in the stories, which is fine, but I'm also seeing placeholder content in the implementation. Can we follow a practice of only using real-world content in the implementation components?

If there isn't any content for a particular thing, that may be an indication that we should split out the effort for that component until we can implement.

2021-01-16 06:04 UTC, Krank3n commented
> Looking mostly good. I can see placeholder content in the stories, which is fine, but I'm also seeing placeholder content in the implementation. Can we follow a practice of only using real-world content in the implementation components?
> 
> If there isn't any content for a particular thing, that may be an indication that we should split out the effort for that component until we can implement.

Yea that makes sense dude.

2021-01-16 09:07 UTC, Krank3n commented
> > Looking mostly good. I can see placeholder content in the stories, which is fine, but I'm also seeing placeholder content in the implementation. Can we follow a practice of only using real-world content in the implementation components?
> > If there isn't any content for a particular thing, that may be an indication that we should split out the effort for that component until we can implement.
> 
> Yea that makes sense dude.

After looking at this again, I remebered the reason I used some of these placeholders was because I couldnt work out how to add images from a folder library.

If I imported it, or add it directly add in like this, webpack throws an error:

![image](https://user-images.githubusercontent.com/45204791/104807894-0f197a80-582e-11eb-8aa8-83a7abfe240d.png)

2021-01-27 06:53 UTC, jakxnz requested changes
Okay! I think there's good progress here. You've demonstrated that we can build some good stuff with CoreUI. I suspect you've gone a bit wild with the copy+paste 😅. Maybe try to be a bit more strategic with each thing you introduce?

My expectation for this feature was that it would be a header and a navigation (i.e mobile and desktop navigation). So all the extra stuff like dropdowns and avatars and stuff don't need to be introduced to fulfil the needs of the header at this point in time. We can build those components as their own thing.

A side effect of that is it's taken me almost an hour to PR all this code, but the scope of the story is much smaller than that. I need that time and energy to focus on other stuff too 😅

Let me know what you think, but ideally it would be good if this Header feature could be kept simple, so we can build on it, rather than cramming everything in wildly, without much strategy around how we want to implement each feature.

2021-01-27 06:53 UTC, jakxnz commented on cypress/integration/Home/Header.spec.js
> +  });
It's good to start with something simple, and we can expand on these as we go along. This might be a bit too simple though. Can we test for things like responsive views? Does an assertion like "Contains a nav item" belong in the Header component? Or is that more related to a nav component?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +const Header = () => (
This seems like a lot going on for one component to me. How much of this stuff actually belongs in its own component?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +import { TheHeaderDropdown } from './TheHeaderDropdown';
Where did this naming convention come from? Is it from CoreUI? If we made it up, can we use something more declarative? i.e Something that describes its role in the app in an identifiable way?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +      />
I tested this toggle, but it doesn't seem to do anything. Is it working at your end?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +      </CHeaderBrand>
Our brand is an envelope? 😅

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +      <CHeaderNav className="d-md-down-none mr-auto">
Can this nav be its own component?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        </CHeaderNavItem>
These nav items don't seem to have any interactivity. Is there something we need to do to get them behaving like buttons?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        </CHeaderNavItem>
Can this be its own component? Also, is this in the scope of the current task? Or do we want to add this when we do a task for search?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +      <CHeaderNav className="px-3">
Can this be its own component?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        <TheHeaderDropdownNotif/>
Is this in the scope of the current task? Or do we want to add this when we do notifications?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        <TheHeaderDropdownTasks/>
Is this in the scope of the current task? Or do we want to add this when we do a "tasks" feature?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        <TheHeaderDropdownMssg/>
Is this in the scope of the current task? Or do we want to add this when we do a "messages" feature?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        </div>
Can this be its own component?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +        </CHeaderNavItem>
These subsequent menu items look like they're repeating markup, so could we render them with a map, rather than static code?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +          </div>
These subsequent menu items look like they're repeating markup, so could we render them with a map, rather than static code?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +      <CSubheader className="px-3 justify-content-between">
Can this be its own component?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/Header.js
> +          <div className="c-subheader-nav-link">
These nav items don't seem to have much interactivity. Is there something we need to do to get them behaving like buttons?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdown.js
> +import User from '../../../images/user_sp.jpg';
Can we use something to handle the path,? e.g https://github.com/entwicklerstube/babel-plugin-root-import , That should also help us with the `Cannot find module '../../../images/user_sp.jpg'` error this code has when visiting in the browser

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdown.js
> +export default { title: 'TheHeaderDropdown' };
What does this do?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdown.js
> +          src={User}
We probably don't want the component to reference a specific image, right? Can we do this with a prop instead?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdown.js
> +      </CDropdownItem>
These subsequent menu items look like they're repeating markup, so could we render them with a map, rather than static code?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdown.stories.js
> +export const TheHeaderDropdown = () => (
Why does this component exist twice? Can we create one component, and use it in both the production code and storybook?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownMssg.stories.js
> +export const TheHeaderDropdownMssg = () => (
Why does this component exist twice? Can we create one component, and use it in both the production code and storybook?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownMssg.js
> +      </CDropdownItem>
These subsequent menu items look like they're repeating markup, so could we render them with a map, rather than static code?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownNotif.js
> +      <CDropdownItem><CIcon content={cilSpeech} name="cil-speedometer" className="mr-2 text-warning"/> Server overloaded</CDropdownItem>
These subsequent menu items look like they're repeating markup, so could we render them with a map, rather than static code?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownNotif.js
> +      </CDropdownItem>
Will we be using this feature for anything?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownNotif.stories.js
> +export const TheHeaderDropdownNotif = () => (
Why does this component exist twice? Can we create one component, and use it in both the production code and storybook?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownTasks.js
> +      </CDropdownItem>
These subsequent menu items look like they're repeating markup, so could we render them with a map, rather than static code?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/TheHeaderDropdownTasks.stories.js
> +export const TheHeaderDropdownTasks = () => (
Why does this component exist twice? Can we create one component, and use it in both the production code and storybook?

2021-01-27 06:53 UTC, jakxnz commented on src/js/components/Header/header.stories.js
> +export const Header = () => (
Why does this component exist twice? Can we create one component, and use it in both the production code and storybook?

2021-01-27 06:53 UTC, jakxnz commented on src/scss/_custom.scss
> +  border-radius: .3em !important;
My preference would be that at all costs we try and avoid using `!important;` it is a death sentence for extensibility. Can you do this with the correct css selector specificity instead? Does this scss need to be placed in a file that is introduced downstream from `_avatars.scss` perhaps?

2021-01-27 06:53 UTC, jakxnz commented on src/stories/forms.storiess.js
> +export default { title: 'BasicForms' };
Is there a typo in this filename?

2021-01-27 06:53 UTC, jakxnz commented on src/stories/forms.storiess.js
> +);
Is this part of the scope of the Header feature?

2021-01-27 08:21 UTC, Krank3n commented on src/js/components/Header/Header.js
> +const Header = () => (
What do you mean by this question? The components are broken up... which I am sure you are aware of, which makes me misunderstand the question

2021-01-27 08:21 UTC, Krank3n commented on src/js/components/Header/Header.js
> +import { TheHeaderDropdown } from './TheHeaderDropdown';
It's from COREUI

2021-01-31 10:27 UTC, Krank3n commented on cypress/integration/Home/Header.spec.js
> +  });
Ok, I have reduced the Nav down to a very basic structure. Removing the drop downs etc. Added some more tests for cypress for responsive views. Though I am having a mind blank on how to test these again. saying cy is not definied. I cant remember how I got past it last time. Im pushing it up in the meantime

2021-03-02 07:54 UTC, Krank3n commented on src/js/components/Header/Header.js
> +      />
Toggle is now working

2021-03-02 07:54 UTC, Krank3n commented on src/js/components/Header/Header.js
> +      </CHeaderBrand>
not anymore haha

2021-03-02 07:55 UTC, Krank3n commented on src/js/components/Header/TheHeaderDropdownTasks.stories.js
> +export const TheHeaderDropdownTasks = () => (
I have removedalot of these components

2021-03-02 07:56 UTC, Krank3n commented on src/js/components/Header/header.stories.js
> +export const Header = () => (
Oh so like import the component into storybook? That can be done like this:

`import React from 'react';
import Header from './Header';

export default {
  title: 'Header',
  component: Header,
};

export function HeaderWith() {
  return (
    <Header />
  );
}
`

2021-03-02 07:58 UTC, Krank3n commented on src/scss/_custom.scss
> +  border-radius: .3em !important;
hmm good point 👯‍♀️

2021-03-02 08:01 UTC, Krank3n commented on src/stories/forms.storiess.js
> +export default { title: 'BasicForms' };
removed

2021-03-02 08:01 UTC, Krank3n commented on src/stories/forms.storiess.js
> +);
removed

2021-03-05 04:02 UTC, jakxnz requested changes
Epic progress. Even at a glance this looks way more like the scope of the feature.

I've raised a few questions and will do some functional tests when I get a chance.

2021-03-05 04:28 UTC, Krank3n commented on package.json
> -    "watch": "webpack --watch",
sure

2021-03-05 04:32 UTC, Krank3n commented on src/js/components/Header/HeaderNavigation.js
> +          ))}
Split into a new component now

2021-03-05 04:36 UTC, Krank3n commented on src/js/components/Header/MobileSidebar.js
> +        ))}
Done

2021-03-05 04:37 UTC, Krank3n commented on src/js/components/Header/MobileSidebarContext.js
> +export default MobileSidebarContext;
Do you mean name it so its not specifically for Mobile?

2021-03-05 20:29 UTC, jakxnz commented on src/js/components/Header/MobileSidebarContext.js
> +export default MobileSidebarContext;
Yeah, like can we just call it `ViewContext` or something?

2021-03-05 21:03 UTC, jakxnz requested changes
Yeah man, this is looking really good. I think the logic is there, so most of my comments are on code-style, which means it's real close. I've run out of time to do functional testing, but I'll try fit that in on the next round.

Looking forward to merging this!

2021-03-05 21:03 UTC, jakxnz commented on .gitignore
> +cypress.env.json
This isn't part of this change set aye? This is the cypress PR?

2021-03-05 21:03 UTC, jakxnz commented on src/js/components/Header/HeaderNavigation.js
> +      <CHeaderBrand className="px-3 d-md-down-none">
Could this be tweaked using a similar suggestion to my comments for `SidebarItems`?

2021-03-05 22:54 UTC, Krank3n commented on webpack.config.js
> +  devServer: {
Oh this was for adding inHot Reload and should be part of webpack-dev-server PR... I'll take it out and put it in that PR... but kinda need it here to work with in the meantime.

2021-03-05 22:56 UTC, Krank3n commented on src/js/components/Header/MobileSidebar.js
> +const MobileSidebar = ({ toggle, setToggleNav }) => (
Renamed it to SidebarNav

2021-03-05 22:56 UTC, Krank3n commented on src/js/components/Header/NavData.js
> +    icon: cilUserPlus,
O for Awesome

2021-03-05 22:57 UTC, Krank3n commented on src/js/components/Header/MobileSidebarContext.js
> +export default MobileSidebarContext;
Called it ViewContext... though the word 'view' sounds a little ambigious to me

2021-03-05 22:59 UTC, Krank3n commented on src/js/components/Header/SidebarItems.js
> +}
legend, thanks for the example

2021-03-05 23:04 UTC, Krank3n commented on src/js/components/Header/SidebarItems.js
> +}
updated

2021-03-06 01:43 UTC, closed without merging