Cypress dependencies
underflip/shredindex-frontend pull request #11
Opened 2020-11-07 01:48 UTC by Krank3n

Added Cypress Dependencies seperately

2020-12-02 01:26 UTC, jakxnz requested changes
Cool man. I'm a little confused sorry, It seems like this PR is dedicated to getting the base cypress stuff in, but I'm not sure what it's base is. What is the base commit for these features? When I try base it on `feature/pattern-library` I get a bunch of Header component commits, and when I try base it on `feature/global-header` I don't see any code I expect. Can we do something line this up so I can see what code is related to the PR?

2020-12-02 01:26 UTC, jakxnz commented on src/js/routes.js
> +export default routes;
Do we want these in our project? Or did that just come along for the ride unintentionally?

2020-12-02 01:26 UTC, jakxnz commented on src/stories/forms.storiess.js
> +import React from 'react';
Is there a spelling mistake in this file name?

2020-12-04 18:48 UTC, Krank3n commented
> Cool man. I'm a little confused sorry, it seems like this PR is dedicated to getting the base cypress stuff in, but I'm not sure what it's base is. What is the base commit for these features? When I try base it on `feature/pattern-library` I get a bunch of Header component commits, and when I try base it on `global-header` I don't see any code I expect. Can we do something line this up so I can see what code is related to the PR?

Sorry for confusion, this should be based off the pattern-library. I haved removed Header component stuff and hopefully everything else unrelated.

2020-12-04 18:48 UTC, Krank3n commented on src/js/routes.js
> +export default routes;
removed

2020-12-04 18:49 UTC, Krank3n commented on src/stories/forms.storiess.js
> +import React from 'react';
I removed this... I think I missed spelt it on purpose so it would crash storyboard.

2021-01-16 05:52 UTC, jakxnz requested changes
This needs a rebase. When that's done I can give it a PR, because it should have the right scope of code then 👍

2021-01-27 08:31 UTC, Krank3n commented
> This needs a rebase. When that's done I can give it a PR, because it should have the right scope of code then 👍

I merged dev back into this branch as a rebase was getting to complex... hopefully you are ok with that

2021-02-03 06:30 UTC, jakxnz requested changes
Nice. Thanks for cleaning up the branch. Just a couple of questions about config files

2021-02-03 06:30 UTC, jakxnz commented on cypress.env.json
> +  "baseUrl": "http://underflip.frontend"
This isn't the base URL in my environment, could we rename this file to `cypress.env.json.dist` perhaps? Then we can each create `cypress.env.json` for our respective environments without messing with the git index

2021-02-03 06:30 UTC, jakxnz commented on .gitignore
> +cypress.json
```suggestion
.idea
cypress/
debug.log
cypress.json
```

Should we be excluding `cypress.json`? Or is that a place we can store shared config, and we each use `cypress.env.json` for environment-specific config?

2021-03-05 03:40 UTC, Krank3n commented on .gitignore
> +cypress.json
My cypress doesnt pick up the cypress.env.json file, needs to be cypress.json

2021-03-06 00:32 UTC, jakxnz approved these changes
LGTM

2021-03-06 01:25 UTC, merged