Header
underflip/shredindex-frontend pull request #16
Opened 2021-03-06 01:44 UTC by Krank3n

Added functional Header and Sidebar

2021-03-06 01:49 UTC, jakxnz requested changes
Mmmmf, loving this progress.

2021-03-06 01:49 UTC, jakxnz commented on src/js/components/Header/HeaderItems.js
> +const HeaderItems = () => {
Hey, I notice that these components are in the `Header` namespace (the `Header` folder). Can we move them to their own folders?

2021-03-06 01:49 UTC, jakxnz commented on src/js/components/Header/SubHeader.js
> +      <CSubheader className="px-3 justify-content-between">
Do we wanna clean this up a bit?

2021-03-06 01:49 UTC, jakxnz commented on src/js/components/Header/header.stories.js
> +}
Is this needed?

2021-03-06 01:49 UTC, jakxnz commented on src/js/components/Header/HeaderNavigation.js
> +      <CHeaderBrand className="px-3 d-md-down-none">
Can we clean this up a bit?

2021-03-06 01:49 UTC, jakxnz commented on src/js/components/Header/Header.js
> +function Header() {
```suggestion

import ViewContext from './ViewContext';

const Header = () => {
```

2021-03-06 01:49 UTC, jakxnz commented on src/js/components/Header/header.stories.js
> +import React from 'react';
Could we move this to `src/stories/components/Header/`?

2021-03-06 02:18 UTC, Krank3n commented on src/js/components/Header/SubHeader.js
> +      <CSubheader className="px-3 justify-content-between">
done

2021-03-06 02:19 UTC, Krank3n commented on src/js/components/Header/header.stories.js
> +import React from 'react';
done

2021-03-06 02:19 UTC, Krank3n commented on src/js/components/Header/header.stories.js
> +}
Yes it is... Storybook wont pick it up without it.

2021-03-06 05:20 UTC, Krank3n commented on src/js/components/Header/Header.js
> +function Header() {
I swear I tried this, and I couldnt nest another const in it. maybe it didnt have the () =>

2021-03-06 05:20 UTC, Krank3n commented on src/js/components/Header/Header.js
> +function Header() {
anyway added thanks dude

2021-03-06 05:33 UTC, Krank3n commented on src/js/components/Header/HeaderItems.js
> +const HeaderItems = () => {
Sub folders?

2021-03-06 06:23 UTC, Krank3n commented on src/js/components/Header/HeaderItems.js
> +const HeaderItems = () => {
Broken them to its own folders

2021-03-06 06:24 UTC, Krank3n commented on src/js/components/Header/SubHeader.js
> +      <CSubheader className="px-3 justify-content-between">
cleaned

2021-03-06 09:30 UTC, jakxnz requested changes
A global header with navigation ✅

![image](https://user-images.githubusercontent.com/1634995/110201984-d2334100-7eca-11eb-8e33-00ef8b2c46b3.png)
![image](https://user-images.githubusercontent.com/1634995/110201993-d8c1b880-7eca-11eb-9144-48b31e5b18df.png)
![image](https://user-images.githubusercontent.com/1634995/110201971-c0519e00-7eca-11eb-966a-d34699ddd650.png)

Routing works:
![image](https://user-images.githubusercontent.com/1634995/110202003-e9722e80-7eca-11eb-880e-992df47a3474.png)

The only issue is the images aren't being referenced in the correct location:
![image](https://user-images.githubusercontent.com/1634995/110202158-bf6d3c00-7ecb-11eb-8990-8447539396ac.png)

( The `src` above should be `dist/1089...`) 

Webpack seems to be dumping the dist images in the `dist/` root, can we output them to `dist/images/`?
![image](https://user-images.githubusercontent.com/1634995/110202057-42da5d80-7ecb-11eb-9836-96f4f07e051a.png)

I also notice that there's a duplicate `index.html` file being generated in the `dist/` folder, can we avoid that somehow?

We also need CI to be passing before we can merge.

2021-03-13 00:41 UTC, jakxnz requested changes
Doing some quick functional tests: I notice that when I use the desktop nav, the app routes as expected, but when I use the mobile nav the app doesn't seem to route and instead the browser just redirects (which then breaks the view, because there's no response - just a `404` - for the URL it redirects to)

![image](https://user-images.githubusercontent.com/1634995/111012679-b87d8680-8401-11eb-8999-c05d62641547.png)

2021-03-13 09:10 UTC, Krank3n commented
Thanks


> Doing some quick functional tests: I notice that when I use the desktop nav, the app routes as expected, but when I use the mobile nav the app doesn't seem to route and instead the browser just redirects (which then breaks the view, because there's no response - just a `404` - for the URL it redirects to)
> 
> ![image](https://user-images.githubusercontent.com/1634995/111012679-b87d8680-8401-11eb-8999-c05d62641547.png)

Hey man, thanks for finding that, should be all good now.

2021-03-14 01:08 UTC, jakxnz approved these changes
LGTM

[](https://tenor.com/view/button-press-the-button-button-mashing-bulb-boy-flip-the-switch-gif-19815853)

Note: The routing isn't working for each sub-url, (i.e navigating directly to `/resorts`) but I don't think that's in-scope for this story, we can remedy that when we focus more on routing.

2021-03-14 01:10 UTC, merged