Global Footer
underflip/shredindex-frontend pull request #18
Opened 2021-03-14 05:15 UTC by Krank3n

2021-03-15 07:11 UTC, jakxnz requested changes
Feels like you put this together pretty easily 😃. I've added question

2021-03-15 07:11 UTC, jakxnz commented on src/scss/_theSupporters.scss
> +  max-width: 1100px;
What determines this `1100px`? Is it needed? Or should we be following our grid system?

2021-03-15 07:11 UTC, jakxnz commented on src/js/components/Supporters/TheSupporters.js
> +          <a href={item.path}>
Do these also need `noreferrer`?

2021-03-15 07:11 UTC, jakxnz commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +          src="https://media-exp1.licdn.com/dms/image/C5603AQFCq5jKlKuFOQ/profile-displayphoto-shrink_200_200/0/1516800185433?e=1620259200&v=beta&t=TEizzz94vIHLCf0t6cUHhIEF10iBBjc-DNAM_7FHsBk"
Could we just use the link to our avatars on github as the src?

2021-03-15 07:11 UTC, jakxnz commented on src/js/components/Footer/TheFooter.js
> +export default React.memo(TheFooter);
Are we doing to bother memoizing stuff? I thought we were gonna go static (i.e NextJS)?

2021-03-16 05:44 UTC, Krank3n commented on src/js/components/Footer/TheFooter.js
> +const TheFooter = () => (
Just based it off how COREUI had it. Didnt put thought into it. I'll change it to Footer.

2021-03-16 06:18 UTC, Krank3n commented on src/js/components/Footer/TheFooter.js
> +      <a className="mr-1" href="https://shredindex.com" target="_blank" rel="noopener noreferrer">ShredIndex</a>
Sure, hope I have done it right.

2021-03-16 06:19 UTC, Krank3n commented on src/js/components/Footer/TheFooter.js
> +      <span className="mr-1">&copy; 2020</span>
sure

2021-03-16 06:19 UTC, Krank3n commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +const UnderFlipTeam = () => (
sure

2021-03-16 06:53 UTC, Krank3n commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +      </div>
sure, only issue with this is, The design is inverted. Which is minor, but cant think of best way to implement. Would I add a style to the data? Or base it off the index of the mapping, to flip the style?

2021-03-16 06:54 UTC, Krank3n commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +          alt="admin@bootstrapmaster.com"
cool

2021-03-16 06:59 UTC, Krank3n commented on src/js/components/Supporters/TheSupporters.js
> +      ))}
ahhhh yes :D

2021-03-16 07:01 UTC, Krank3n commented on src/scss/_theSupporters.scss
> +  max-width: 1100px;
Not needed, just looks better, I am trying to think if there is a way to add this using our current grid system... any ideas?

2021-03-16 07:02 UTC, Krank3n commented on src/js/components/Supporters/TheSupporters.js
> +          <a href={item.path}>
taken out

2021-03-16 07:02 UTC, Krank3n commented on src/js/components/Footer/TheFooter.js
> +export default React.memo(TheFooter);
Taken Out

2021-03-16 07:04 UTC, Krank3n commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +          src="https://media-exp1.licdn.com/dms/image/C5603AQFCq5jKlKuFOQ/profile-displayphoto-shrink_200_200/0/1516800185433?e=1620259200&v=beta&t=TEizzz94vIHLCf0t6cUHhIEF10iBBjc-DNAM_7FHsBk"
can I flip your photo around so we are looking opposite directs lol?

2021-03-17 07:24 UTC, jakxnz requested changes
Looking good man. Codes getting better by the feature!

**Requirements**

A global footer with navigation *️⃣

Navigation *️⃣
![image](https://user-images.githubusercontent.com/1634995/111430044-b186a900-875e-11eb-88f1-3b707de7dce3.png)

We've already talk about an inbound nav here too.

Copyright ✅

![image](https://user-images.githubusercontent.com/1634995/111430107-cd8a4a80-875e-11eb-99b9-e3adb21c0c99.png)

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/SupportItems/SupportItems.js
> +    {SupportService
Can this be simplified?

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/SupportItems/SupportItems.js
> +          <a href={item.path}>
Can we add `noopener noreferrer` here?

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/TeamMember/TeamMember.js
> +  <>
Does this need the `<>` fragment?

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +    {TeamConfig
Can this be simplified?

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +const UnderFlipTeam = () => (
"Underflip" is one word right? So is this component's name `UnderflipTeam`?

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +);
```suggestion
const UnderFlipTeam = () => TeamConfig.map((item) => <TeamMember member={item} />);
```

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/config/team-config.js
> +    imgSrc: 'https://avatars.githubusercontent.com/u/1634995?s=60&u=ebaca76ccf999d03b9259721d800571f6df7a6a4&v=4',
```suggestion
    name: 'jakxnz',
    path: 'https://github.com/jakxnz',
    imgSrc: 'https://avatars.githubusercontent.com/u/1634995?s=60&u=ebaca76ccf999d03b9259721d800571f6df7a6a4&v=4',
```

I'm not picky, but while I'm here 😂

2021-03-17 07:24 UTC, jakxnz commented on src/scss/_theSupporters.scss
> +  max-width: 1100px;
As in, bootstrap? `class="container"`?

2021-03-17 07:24 UTC, jakxnz commented on src/scss/style.scss
> +@import "theFooter";
Do we need the `the` prefix?

2021-03-17 07:24 UTC, jakxnz commented on src/js/components/TeamMember/TeamMember.js
> +          <a href={props.member.path} target="_blank" rel="noopener">
```suggestion
          <a href={props.member.path} target="_blank" rel="noopener noreferrer">
```

2021-03-17 07:27 UTC, jakxnz commented on src/js/components/config/team-config.js
> +    imgSrc: 'https://avatars.githubusercontent.com/u/1634995?s=60&u=ebaca76ccf999d03b9259721d800571f6df7a6a4&v=4',
Also, is the 60px size enough for retina? Or do we want to go for 120 to be safe?

2021-03-17 07:28 UTC, jakxnz commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +          src="https://media-exp1.licdn.com/dms/image/C5603AQFCq5jKlKuFOQ/profile-displayphoto-shrink_200_200/0/1516800185433?e=1620259200&v=beta&t=TEizzz94vIHLCf0t6cUHhIEF10iBBjc-DNAM_7FHsBk"
Aha! If you like 😂 Doesn't bother me

2021-03-17 07:29 UTC, jakxnz commented on src/js/components/Footer/TheFooter.js
> +export default React.memo(TheFooter);
Is it?

2021-03-17 08:05 UTC, Krank3n commented on src/js/components/Footer/Footer.js
> +  const productUrl = 'https://shredindex.com';
cool

2021-03-17 08:16 UTC, Krank3n commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +const UnderFlipTeam = () => (
nice

2021-03-24 07:12 UTC, jakxnz requested changes
Getting cleaner and cleaner man! Keep it coming. Added a few more questions

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/Footer/Footer.js
> +      <a href={ProductOverview.underFlip.url} target="_blank" rel="noopener ">{ProductOverview.underFlip.name}</a>
Can we use destructuring here?

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNavList = () => NavConfig.map((item) => (
Nice.

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +export default FooterNav;
Preferably put exports at the bottom of the document, so they're easy to reference

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/SupportBanner/SupportBanner.js
> +  .map((item) => (
```suggestion
export const SupportItems = () => SupportService.map((item) => (
```

Is there a reason for dropping the line?

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNavList = () => NavConfig.map((item) => (
`item` is a little vague to me. If you keep using this everywhere it'll lose all meaning. Can this variable be more declarative?

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/TeamMember/TeamMember.js
> +        src={props.member.imgSrc}
Can you use destructuring for `props.member`? (Don't our linter rules prefer destructuring)?

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/UnderflipTeam/UnderFlipTeam.js
> +  ));
```suggestion
const UnderflipTeam = () => TeamConfig.map((item) => <TeamMember member={item} />);
```
Any reason for making this so many lines?

2021-03-24 07:12 UTC, jakxnz commented on src/js/components/config/supporter-config.js
> +const SupportService = [
This isn't a service pattern, so can this name be more declarative?

2021-04-24 02:00 UTC, jakxnz requested changes
Yeah dude! This code is looking super tidy. Man, such a huge improvement over the life of this PR.

I've pushed a commit to resolve the spelling linting issue you were having, and added a few questions and comments.

Also, do you think you could squash this before the next review? 15 commits is quite a few for a component this size 😅

2021-04-25 02:27 UTC, Krank3n reviewed
> I've pushed a commit to resolve the spelling linting issue you were having, and added a few questions and comments.

Thank you so much dude

2021-04-25 02:28 UTC, Krank3n commented on .eslintrc.json
> +        "plugin:import/typescript"
Sorry this was me trying to fix the linting errors... I'll take it out

2021-04-25 04:52 UTC, Krank3n commented on src/js/components/Footer/Footer.js
> +        <span className="mr-1">Developed by</span>
done

2021-04-25 04:52 UTC, Krank3n commented on src/js/components/SupportBanner/SupportBanner.js
> +    <a href={support.url} rel="noopener noreferrer">
yea I'll add some

2021-04-25 05:05 UTC, Krank3n commented on src/scss/_custom.scss
> +  width: 70px;
added

2021-04-25 05:06 UTC, Krank3n commented on src/scss/_supporters.scss
> +  //max-width: 1100px;
removed

2021-04-25 05:06 UTC, Krank3n commented on src/scss/_custom.scss
> +  border-color: $primary;
Maybe why do you ask?

2021-04-25 10:20 UTC, jakxnz commented on src/scss/_custom.scss
> +  border-color: $primary;
As far as I'm aware, `var()` has better compatibility with browsers, and is easier to debug.

2021-04-30 22:30 UTC, jakxnz approved these changes
It's gooooooooooood! 🚦 🟢🟢🟢🟢🟢🟢🟢🟢🟢🟢

2021-04-30 23:29 UTC, merged