Resort Single Page Minimal Frontend
underflip/shredindex-frontend pull request #26
Opened 2021-05-30 10:13 UTC by Krank3n

Displays Resorts
Resort header
Location
Ratings
Numerics 
Generics

2021-05-30 11:15 UTC, jakxnz requested changes
Some really cool stuff happening here. Trying new things, I like it. Great to finally see the `BrowserRouter` gets used for more than basics. I got a bunch of questions, hopefully they're helpful!

Also, this looks like it still needs to be rebased onto latest `develop`.

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +  if (error) return `Error! ${error}`;
I figure because we don't have an error convention, it's better just to let the application break than keep random stuff like this in the repo.

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/ResortHeader/ResortHeader.js
> +        <span className="state-name">{state && state.name ? state.name + ' ' | ' ' : ''}</span>
```suggestion
        {state && state.name &&
            <span className="state-name">state.name</span>
        }
```

https://reactjs.org/docs/conditional-rendering.html

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/ResortHeader/ResortHeader.js
> +        <span className="state-name">{state && state.name ? state.name + ' ' | ' ' : ''}</span>
Also, as I mentioned on slack. The logic in `state && state.name` is a bit weak. The reason is, it's only checking is `state` is truthy. If `state` was a string, this code would break the app. So it's lucky we have `propTypes` protecting us, though that's not very well declared by this logic.

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Resort/Resort.js
> +  const urlID = useParams().name || props.urlID;
Could you clarify what the purpose of this is? Is it so that you can use `BrowserRouter` and the component, standalone? It seems odd to use `props` here when you have a hook that does the job.

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Resort/Resort.js
> +  if (error) return `Error! ${error}`;
I figure because we don't have an error convention, it's better just to let the application break than keep random stuff like this in the repo.

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Ratings/Ratings.js
> +                    <CProgress color="gradient-warning" value={rating.value} max={100} showPercentage className="resort-rating__value font-weight-bold" />
Could you break this line?

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Ratings/Ratings.js
> +            {ratings.map((rating) => (
```suggestion
            {ratings.map(({ id, title, icon, value }) => (
```

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Ratings/Ratings.js
> +        <span className="h6">Ratings</span>
Can this be added to the language setup? (and used FormattedMessage)

Is this just a `span` or do we legitimately want crawlers to know this a meaningful title, i.e make it an `h6`?

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Layout/Layout.js
> +                  {NavConfig.map((route) => route.component && (
```suggestion
                  {NavConfig.map(({ path, exact, name }) => route.component && (
```

2021-05-30 11:15 UTC, jakxnz commented on src/js/app.js
> +          <Route path="/" name="Home" render={(props) => <Layout {...props} />} />
Something seems strange about this. Why does this use the `render` prop and not just passing the `<Layout>` component as children?

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Layout/Layout.js
> +                  />
I'm confused. So we have routes in the `App` component, and we have routes here? What is this doing for us?

2021-05-30 11:15 UTC, jakxnz commented on src/js/components/Home/Home.js
> +      </div>
Mmmm, I've also done this in #23, so we're gonna get a merge conflict.

2021-06-01 03:34 UTC, jakxnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Single resort page](https://trello.com/c/WWkqTriT/12-single-resort-page)

2021-06-05 01:59 UTC, Krank3n commented on src/js/components/Description/Description.js
> +const Description = (props) => (
Possibly in the future, but not at the moment.

2021-06-05 03:59 UTC, Krank3n commented on src/js/components/Sidebar/SidebarItems.js
> +  const filtered = NavConfig.filter((item) => item.name !== 'Home' && item.name !== 'Resort');
So should this be called RoutingConfig?

2021-06-05 04:01 UTC, Krank3n commented on src/js/components/Statistics/Statistics.js
> +        <span className="h6">Statistics</span>
Sure

2021-06-05 04:17 UTC, Krank3n commented on src/js/components/Statistics/Statistics.js
> +});
nice

2021-06-05 04:19 UTC, Krank3n commented on src/js/components/config/nav-config.js
> +    component: Home,
Hmm, I put in what you suggested earlier, and renamed it routes.

2021-06-05 04:21 UTC, Krank3n commented on src/stories/Resort/Resort.stories.js
> +      initialEntries={[{ pathname: '/yes' }]}
Oh yea, sorry I left this in here, because I couldn't get this MemoryRouter working and I ended up passing the path as a prop. Let me take it out in the meantime.

2021-06-05 04:22 UTC, Krank3n commented on src/js/components/Resorts/Resorts.js
> +  if (error) return `Error! ${error}`;
hmmm ok

2021-06-05 04:24 UTC, Krank3n commented on src/js/components/ResortHeader/ResortHeader.js
> +        <span className="state-name">{state && state.name ? state.name + ' ' | ' ' : ''}</span>
I didnt realise you can write syntax like this.

2021-06-05 04:27 UTC, Krank3n commented on src/js/components/Ratings/Ratings.js
> +            {ratings.map((rating) => (
Linting broke this line to me so its like 
`            {ratings.map(({
              id, title, icon, value,
            }) => (`

2021-06-05 04:27 UTC, Krank3n commented on src/js/components/Ratings/Ratings.js
> +            {ratings.map((rating) => (
ehhh that didnt work

2021-06-05 04:29 UTC, Krank3n commented on src/js/components/Ratings/Ratings.js
> +        <span className="h6">Ratings</span>
If its a Formatted message, should I just add the class as h6? Or put an h6 element inside it?

2021-06-05 04:39 UTC, Krank3n commented on src/js/app.js
> +          <Route path="/" name="Home" render={(props) => <Layout {...props} />} />
Think I tried it that way initially and it didn't work. Just tested it again, it works for home page, but the other pages don't render. Will have to look into this further if we want to change it.

2021-06-05 04:41 UTC, Krank3n commented on src/js/components/Layout/Layout.js
> +                  />
Dont we have to delare the routes in the App component, and we want to keep the initial layout, so we add Routes here?

2021-06-07 03:21 UTC, jakxnz requested changes
Getting better!

2021-06-07 03:21 UTC, jakxnz commented on src/js/components/Resort/Resort.js
> +        {skeletonState}
Aha man, you really defined this inside the `Resort` component! I was meaning as a separate `const LoadingSkeleton = () => {` component. So it can be `<LoadingSkeleton />`. No stress, we'll be refactoring this anyway, so I'll approve this with the intention of revising it later.

2021-06-07 03:21 UTC, jakxnz commented on src/js/components/ResortHeader/ResortHeader.js
> +        )}
Could this just be...

```
{(state && state.name) && <span className="resort-header__state-name">{`${state.name} | `}</span>}
```

2021-06-07 03:21 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +          {resort.title}
Can you object destructure `resort`?

2021-06-07 03:21 UTC, jakxnz commented on src/js/components/Statistics/Statistics.js
> +          id="shredindex.statistic.STATISTICS"
`shredindex.statistics`

2021-06-07 03:21 UTC, jakxnz commented on src/stories/Resort/Resort.stories.js
> +      <ResortComponent urlID={mocks.resort.request.variables.id} />
I'm surprised this isn't doable with `MemoryRouter`

2021-06-07 03:21 UTC, jakxnz commented on src/js/components/config/routing-config.js
> +const RoutingConfig = [
This isn't a component, so should it be `routingConfig`?

2021-06-07 03:21 UTC, jakxnz commented on src/js/components/Sidebar/SidebarItems.js
> +  const filtered = RoutingConfig.filter((item) => item.showInMenu);
Nice.

2021-06-20 07:30 UTC, Krank3n commented on src/js/components/Layout/Layout.js
> +                    route, path, exact, name,
I tried working alternatively with this, I think I may need some help to remove the 'route.component'

2021-06-20 07:30 UTC, Krank3n commented on src/js/components/Ratings/Ratings.js
> +          id="shredindex.rating.RATINGS"
ok

2021-06-20 07:56 UTC, Krank3n commented on src/js/components/Resorts/Resorts.js
> +          {resort.title}
![image](https://user-images.githubusercontent.com/45204791/122666480-cc9b0600-d1f0-11eb-9fb4-6ba4fe936956.png)

`resortsData.map(
      ({
        resort: {
          id: ID,
          url_segment: urlSegment,
          title,
        },
      }) => (
        <div key={ID} className="px-3">
          <Link className="resort-link" to={`${props.match.path}/${ID}/${urlSegment}`}>
            {title}
          </Link>
        </div>
      ),
    )`
getting frustrated with this.

2021-06-20 07:58 UTC, Krank3n commented on src/js/components/config/routing-config.js
> +const RoutingConfig = [
oh ok 👯‍♂️

2021-06-20 08:00 UTC, Krank3n commented on cypress/integration/Resort/Resort.spec.js
> +    cy.get('.resort-ratings__card').should('be.visible');
Removed this

2021-06-25 23:34 UTC, jakxnz requested changes
Nice man. This is looking really good. I've noticed a few things while manual testing, so have left a few more comments and questions.

Do we need this spacing?
![image](https://user-images.githubusercontent.com/1634995/123493986-6b50b800-d672-11eb-8ece-566772bb9d34.png)

Manual testing looking good:

A page that displays the details of a single resort ✅
- Should have an SEO'd URL ✅
- Displays all statistics and info ✅

![image](https://user-images.githubusercontent.com/1634995/123493913-2cbafd80-d672-11eb-8b51-90eb6909c705.png)
![image](https://user-images.githubusercontent.com/1634995/123493927-347aa200-d672-11eb-8284-966025846f61.png)
![image](https://user-images.githubusercontent.com/1634995/123493934-39d7ec80-d672-11eb-8381-5ad1e4eae1d4.png)

2021-06-25 23:34 UTC, jakxnz commented on src/stories/Resorts/Resorts.stories.js
> +export const Resorts = () => {
(Passing through on another PR) Can we remove this story (because it's just a placeholder component)?

2021-06-25 23:34 UTC, jakxnz commented on src/stories/components/Preloader/Preloader.stories.js
> +export const Preloader = () => {
Wasn't this added in a previous PR, why is it showing up here?

2021-06-25 23:34 UTC, jakxnz commented on src/stories/components/SupportBanner/SupportBanner.stories.js
> +export const SupportBanner = () => {
Wasn't this added in a previous PR, why is it showing up here?

2021-06-25 23:34 UTC, jakxnz commented on codecov.yml
> +coverage:
Wasn't this added in a previous PR, why is it showing up here?

2021-06-25 23:58 UTC, Krank3n commented on codecov.yml
> +coverage:
hmmm not sure... Maybe todo with rebasing from dev?

2021-06-25 23:59 UTC, Krank3n commented on cypress/integration/Resorts/Resorts.spec.js
> +describe('Resort', () => {
so take out the test for resorts?

2021-06-26 00:14 UTC, Krank3n commented on src/js/components/Resort/Resort.js
> +          <span className="h6">Description</span>
Maybe a h3 with a h6 class

2021-06-26 00:21 UTC, Krank3n commented on src/js/components/Resort/Resort.js
> +            <p className="description">{description}</p>
Nah I didnt really understand this format, kinda get it now after some research.

2021-06-26 00:23 UTC, Krank3n commented on src/js/components/SidebarNav/SidebarNav.js
> +const SidebarNav = () => {
I think it was becase of the Rebase with Dev... dev had the file in a different location.

2021-06-26 00:25 UTC, Krank3n commented on src/js/components/SkeletonState/LoadingSkeleton.js
> +const LoadingSkeleton = (
yea, I had the feeling from you we would be able to manipulate it for different components depending on the situation. But yea can definitely make it component specific

2021-06-26 00:27 UTC, Krank3n commented on src/js/components/SkeletonState/LoadingSkeleton.js
> +const LoadingSkeleton = (
yea, I getcha 👯

2021-06-26 00:31 UTC, Krank3n commented on src/js/components/SkeletonState/LoadingSkeleton.js
> +    <CCard className="skeleton-card p-5" />
Haha, how does one work out the size of the content when the data isn't retrieved yet?

How much love and attention should we give this now?

2021-06-26 01:29 UTC, Krank3n commented on src/js/components/Statistics/Statistics.js
> +    <CCard className="resort-statistics__card">
Yes correct :D

2021-06-26 01:34 UTC, Krank3n commented on src/js/components/Statistics/Statistics.js
> +    <CCard className="resort-statistics__card">
sorry I dont remember seeing this 27 days ago 🗡️

2021-06-26 01:37 UTC, Krank3n commented on src/js/components/Statistics/Statistics.js
> +                    <CProgress color="gradient-warning" value={value} max={100} showPercentage className="resort-statistic__value font-weight-bold" />
Yea, didint put love into this, because I know we will refactor it, I assume relatively early? But still interested in what you mean by skinning it. I just thought I would use the class because this hasn't been designed yet and didn't want to ad any extra fluff.

2021-06-26 01:40 UTC, Krank3n commented on src/js/components/config/product-overview-config.js
> +const ProductOverview = {
ok

2021-06-26 01:41 UTC, Krank3n commented on src/js/lang/en.json
> +    "shredindex.app.SUBTITLE": "Live your best adventure lifestyle",
Not anymore.

2021-06-26 01:45 UTC, Krank3n commented on src/stories/Resorts/Resorts.stories.js
> +export const Resorts = () => {
sure

2021-07-03 07:53 UTC, jakxnz requested changes
I think this feature has achieved what you set out to do. I've raised questions about the last few minor things, so let's get 'em done and we can merge this bad boy!

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +    cy.get('.resort__description-content').should('be.visible');
Can this test quantify something, rather than just confirm something that's inevitable?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +    cy.get('.ratings-list').should('be.visible');
Can this test quantify something, rather than just confirm something that's inevitable?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +  dataProvider.ratings.forEach((data) => {
Why is this a data provider, when there's only one variation? Do you intend on adding more variants to the data provider?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +        .should('be.visible');
Can this test quantify something, rather than just confirm something that's inevitable?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +  dataProvider.numerics.forEach((data) => {
Why is this a data provider, when there's only one variation? Do you intend on adding more variants to the data provider?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +        .should('be.visible');
Can this test quantify something, rather than just confirm something that's inevitable?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +        .should('be.visible');
Can this test quantify something, rather than just confirm something that's inevitable?

2021-07-03 07:53 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +});
What I see you doing a lot is testing the "internal implementation". It's not helpful to do that, because it doesn't prove anything. Instead, we want to test the behaviour. Here's a couple of articles that might gives you some ideas on how to write better tests:

https://ruleoftech.com/2019/notes-of-best-practices-for-writing-cypress-tests
https://blog.logrocket.com/javascript-testing-best-practices/

2021-07-03 07:53 UTC, jakxnz commented on src/js/components/SkeletonState/ResortSkeleton.js
> +const ResortSkeleton = () => (
I'm guessing you're not gonna do what we suggested during our Discord chat as part of this PR. So I've raised a Trello card so we can do it later https://trello.com/c/tvLKXC5M

2021-07-03 07:53 UTC, jakxnz commented on src/js/components/config/routing-config.js
> +    path: '/Resorts/:name/:country',
Does this match anything? Is it used anywhere?

2021-07-03 21:30 UTC, Krank3n commented on src/js/components/SkeletonState/ResortSkeleton.js
> +const ResortSkeleton = () => (
I cant remember exactly which part of the skeleton you are talking about. My thinking was to go through the design process first?

2021-07-03 21:30 UTC, Krank3n commented on src/js/components/config/routing-config.js
> +    path: '/Resorts/:name/:country',
Yea I dont think thats needed anymore, I took it out and tested it. seems fine without it. Good find.

2021-07-03 21:30 UTC, Krank3n commented on cypress/integration/Resort/Resort.spec.js
> +});
thanks man

2021-07-04 01:41 UTC, jakxnz commented on src/js/components/SkeletonState/ResortSkeleton.js
> +const ResortSkeleton = () => (
We can chat about it on Slack 👍

2021-07-04 02:41 UTC, jakxnz approved these changes
You got it there! Nice one dude! Amazing to see the difference between the branch now compared to when you first raised the PR. Epic progress.

LGTM

2021-07-04 02:52 UTC, merged