CoreUI 4.0 Migrate
underflip/shredindex-frontend pull request #32
Opened 2021-10-22 07:11 UTC by Krank3n

CoreUI 4.0  Migrate
React Update
Webpack Update
Apollo Update

2021-10-25 00:56 UTC, jakxnz requested changes
Looking pretty good so far. Will give it a practical test on the next reivew

2021-10-25 00:56 UTC, jakxnz commented on .babelrc
>      ]
Can this be simplified?

```
"@babel/plugin-transform-runtime",
"@babel/plugin-proposal-class-properties"
```

2021-10-25 00:56 UTC, jakxnz commented on cypress/integration/Header/Header.spec.js
> +    it('Breadcrumb name should be title case', () => {
```suggestion
    it('Should display breadcrumbs with title case', () => {
```

2021-10-25 00:56 UTC, jakxnz commented on cypress/integration/Resort/Resort.spec.js
> +    cy.get('.rating__value').children('.progress').children('.progress-bar').should('have.attr', 'aria-valuenow', '76');
Seems odd to need to do `.children()` twice? Maybe `.within()` is what you're looking for?

2021-10-25 00:56 UTC, jakxnz commented on package.json
> +    "react-router-dom": "^5.3.0"
❤️

2021-10-25 00:56 UTC, jakxnz commented on src/js/components/Footer/Footer.js
> +import { CFooter, CImage } from '@coreui/react';
Finally, people have stopped using "img"!

2021-10-25 00:56 UTC, jakxnz commented on src/js/components/Header/Header.js
> +          <CIcon icon={item.icon} className="header-nav__icon me-2" />
Interesting. What does `me` do? "Margin end" or something?

2021-10-25 00:56 UTC, jakxnz commented on src/js/components/SubHeader/SubHeader.js
> +    <>
No more breadcrumb router?

2021-10-25 00:56 UTC, jakxnz commented on src/scss/_custom.scss
> +  box-shadow: 0 0 0.6rem var(--cui-btn-shadow);
Our upgrade needed box shadows 😅?

2021-10-31 01:40 UTC, Krank3n commented on src/stories/coreui/Buttons.stories.js
> +            <CRow className="align-items-center mb-3" key={i}>
Yea thanks for the heads up on this.

2021-10-31 01:41 UTC, Krank3n commented on src/stories/coreui/Buttons.stories.js
> +                    key={ind}
yea... I took out 'ind' and replaced with index.

Still need two variables as they are nested and will conflict

2021-10-31 01:42 UTC, Krank3n commented on .nvmrc
> +16.0.0
Yep changed that thanks dude

2021-10-31 07:37 UTC, jakxnz approved these changes
Punch it!

2021-10-31 07:38 UTC, merged

2021-10-31 07:38 UTC, jakxnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [CoreUI 4.0 Migrate](https://trello.com/c/jLMpqPm5/70-coreui-40-migrate)