Resort Card
underflip/shredindex-frontend pull request #33
Opened 2021-11-09 08:07 UTC by Krank3n

Resort Title
Description
Total Score
Highlights & Lowlights Scores
Image Carousel
Comment Carousel
Expand and Collapse

2021-11-10 01:30 UTC, jakxnz requested changes
Here's my first pass.

Could you please refactor all uses of `{ ... } => props` to follow the example I've given of restructuring in the component function declaration?

Is there a chance you're over-done the proptypes? You only need to declare the proptypes that the component uses, anything else is superfluous (or possible even in the wrong scope).

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +import React from 'react';
What is a "resort card skeleton list"? (Is there a better name for this?)

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +    </div>
Is there a way to do this with less repetition?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +
```suggestion
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  const [collapsed, setCollapsed] = useState(true);
If I refresh the page, do we want to keep the user's expanded cards?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  const { url_segment } = props;
Instead of destructuring this here, could you restructure it in the component declaration?

```
function ResortCard({ urlSegment }) {
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  const { url_segment } = props;
Also, should the `url_segment` prop be camelcased instead of snakecased?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  }
Is this something we should do on the front-end? What if we change the spelling of "Total Shred Score"?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  }
Is there any way to make this more readable?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +  } = props;
```suggestion
const ResortCardBody = ({
  resort: {
    location,
      description,
      highlights,
      lowlights,
      resort_images,
      comments,
  }
}) => {
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +              scores={highlights}
Are they "scores" or "ratings"?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +  resort: ResortType.isRequired,
Do you really need so many prototypes for this component? I don't see you using all of these things in this component?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardCommentCarousel/ResortCardCommetCarousel.js
> +              &quot;
```suggestion
              {`&quot;${comment}&quot;`}
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardCommentCarousel/ResortCardCommetCarousel.js
> +              {author}
```suggestion
              {`- ${author}`}
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        ))}
```suggestion
        {images.map(({ id, name, image, }) => (
          <img key={id} className="w-100" src={image ? image.path : resortImagePlaceholder} alt={name} />
        ))}
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +  const flag = `https://flagcdn.com/${countryCode.toLowerCase()}.svg`;
Could you use a hook here, so this component doesn't need to know the flagcdn concerns?

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +        <div key={id} className="">
```suggestion
        <div key={id}>
```

2021-11-10 01:30 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +        <div key={id} className="">
What role does this `<div` fulfil?

2021-11-10 01:46 UTC, Krank3n commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +      <Link className="resort-link" to={`resorts/${url_segment}`}>
Do you mean, add it too the backend GraphQL Schema? 

like 
URL: STRING

"resorts/whistler-blackcomb"

2021-11-10 01:47 UTC, Krank3n commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +          {collapsed ? null : <span className="me-2 fade-in">Go to resort </span>}
Not sure what you are getting at here sorry?

2021-11-10 01:52 UTC, Krank3n commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +import React from 'react';
A resortCardSkeletonList is the Skeleton state of a Card, in a list.

I wasn't sure, at what point the skeleton state for the card/s should be shown?

Maybe this should be just one skeleton per resort card, but I found that, it made the skeleton state kinda redundant as the list of resorts took a long time to load, not the individual card.

2021-11-10 01:53 UTC, Krank3n commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +    </div>
Yea, let me have a look. Maybe wait for your feedback if we want this list first?

2021-11-10 01:53 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +
thanks

2021-11-10 01:53 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  const [collapsed, setCollapsed] = useState(true);
I guess that would be nice,

should we be using Context for this?

2021-11-10 01:57 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  }
I was trying to work this out in the backend. But couldn't work out how to get the total score :(
I didn't like thinking about the changing of the spelling here when I wrote it, but wont we have to reference that in a similar way from the backend?

2021-11-10 01:58 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +              scores={highlights}
I guess we should keep them as Ratings everywhere, since it's already in the backend like that?

2021-11-10 02:00 UTC, Krank3n commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +  const flag = `https://flagcdn.com/${countryCode.toLowerCase()}.svg`;
Seperate this into another component?

Sorry im not too sure what you mean?

2021-11-10 22:27 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  const { url_segment } = props;
I thought it was more typical for it to be snakecased?
![image](https://user-images.githubusercontent.com/45204791/141203832-364a0f21-1bde-4174-abd7-fb6b6aac6464.png)

2021-11-10 22:31 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +              scores={highlights}
Ive gone through everything and changed all 'score' to 'rating'

2021-11-10 22:36 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +  resort: ResortType.isRequired,
Do I not need to break the types down?

can I just keep them as an array of a generic object??

![image](https://user-images.githubusercontent.com/45204791/141204818-aa570385-768f-41be-933f-dae0c626cf06.png)

2021-11-10 22:37 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        ))}
thanks for this one dude :)

2021-11-10 23:18 UTC, jakxnz commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +      <Link className="resort-link" to={`resorts/${url_segment}`}>
Exactly

2021-11-10 23:19 UTC, jakxnz commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +          {collapsed ? null : <span className="me-2 fade-in">Go to resort </span>}
i18n = internationalisation = multi-language = `<FormattedMessage ...`

2021-11-10 23:21 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  const [collapsed, setCollapsed] = useState(true);
Nah, you'll need to use either sessionStorage, localStorage or URL params

2021-11-11 00:18 UTC, Krank3n commented on src/js/components/Resorts/Resorts.js
> +        <div key={id} className="">
Oh sorry, i must of left it here, I think I was using it for loading the Skeleton Card State

2021-11-16 20:54 UTC, jakxnz requested changes
Second 1/2 of my first pass. Will checkout your changes for my previous comments in the next pass

2021-11-16 20:54 UTC, jakxnz commented on src/js/components/ResortRatings/ResortRatings.js
> +          defaultMessage="ResortRatings"
```suggestion
          defaultMessage="Resort ratings"
```

2021-11-16 20:54 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +        <div key={id} className="">
I've also suggested removing the empty `className` attribute

2021-11-16 20:54 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeleton.js
> +        </div>
Could this me a component, instead of just repeating the markup over and over?

2021-11-16 20:54 UTC, jakxnz commented on src/scss/_custom.scss
> +  &-1 {
That old counting system 2, 4, 6, 8, 1 😂

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_carousel.scss
> +.resort-card__comment {
[Nitpick] From a BEM perspective, this selector doesn't belong in `_carousel.scss`, there should be a `.carousel` selector to represent this element

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_ratings.scss
> +}
[Nitpick] Names here don't seem to match the file

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_resort-cards.scss
> +
```suggestion
```

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_resort-cards.scss
> +
```suggestion
```

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_resort-cards.scss
> +.skeleton-card__header {
Could these styled be named after the component? Or moved to their own partial?

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_resort-cards.scss
> +.skel-rating-title {
[Nitpick] If I search the codebase for "skele" I'll miss all these styles. Would it be more use-able if these were the full word?

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_resort-cards.scss
> +}
I notice some things are `rem` and some things are `px` in this file. Can we make them all `rem`?

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_ratings.scss
> +}
Can some of the things in this file be `rem`? (Probably just the things that aren't presentational, like a 1px or 2px border or shape)

2021-11-16 20:54 UTC, jakxnz commented on src/scss/components/_flickityCarousel.scss
> +}
Can any `px`s in this file be `rem`s?

2021-11-18 05:00 UTC, Krank3n commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +import React from 'react';
Yea sorry I am not sure why I changed the Resort to load the ResortCardSkeletons. 
I changed that back to ResortSkeleton.

I wasn't sure how to get the fade effect if the Resorts Page was loading multiple cards.

so instead of this:

![image](https://user-images.githubusercontent.com/45204791/142354693-057dba03-5ee6-4368-88c1-997abdaa9488.png)


I could be loading one card... but how do we know how many cards there are, to change the color/ opacity of a for loop/map?

2021-11-18 05:04 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  const { url_segment } = props;
I see, so because we are not using the url_segment as a field it should be CamelCase, but now that I have added the URL field to the Graph that will be snake-case

2021-11-18 05:24 UTC, Krank3n commented on src/scss/components/_resort-cards.scss
> +.skel-rating-title {
changed them to skeleton

2021-11-18 05:26 UTC, Krank3n commented on src/scss/components/_resort-cards.scss
> +}
Yea... i started using pixels when I came across that issue with my monitor displaying at 150%.

I'll spend some time get them to rem.

2021-11-18 06:22 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  const { url_segment } = props;
Yep, when declaring props you use camelCase, and when you're interfacing with a graphQL query, you use snake_case. Just because something called `urlSegment` has the value you want for `url_segment` doesn't mean they follow the same naming convention

2021-11-18 06:26 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +import React from 'react';
There's a lot of ways to solve this. The simplest is to just display a fixed number of loading skeletons. It's definitely possible to do a real-count loading view, but it takes a lot of performance optimisation and sequencing. If you just display 6 loading skeletons every time, that's a good starting point. If you want them to have a fade effect, just use `scss` i.e `.selector:eq(0) { opacity: 1 }, .selector:eq(1) { opacity: 0.8 }` etc

2021-11-18 06:43 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +  };
Would it be possible to do this with `scss`? The component shouldn't really be concerned with the aesthetic, when you already have `scss` for that. e.g

`{filename}.scss`:
```
.rating__bar-20 {
  background-color: var(--cui-secondary);
}

.rating__number-20 {
  border-color: var(--cui-secondary);
}
```

`Rating.js`:

```
 <div className={`rating__bar-${Math.ceil(rating / 20) * 20}` ...
```

2021-11-18 22:37 UTC, Krank3n commented on src/js/components/Rating/Rating.js
> +  };
thanks for that insight dude

2021-11-23 04:43 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        ))}
This actually had to be changed... becuase it needed to check images first, not image inside the array.

`   {images.length > 0 ? images.map(({ id, name, image }) => (
          <img key={id} className="w-100" src={image.path} alt={name} />
        ))
          : <img className="w-100" src={resortImagePlaceholder} alt={name} />}
    `

2021-11-27 05:44 UTC, Krank3n commented on src/js/components/SkeletonState/ResortCardSkeletonList.js
> +import React from 'react';
isnt eq(0) used for jquery only?

I tried using it with no luck?

2021-12-09 07:32 UTC, jakxnz requested changes
This is looking really nice man and is pretty close! I haven't done a practical test yet, but I noticed a few things on my most recent review.

2021-12-09 07:32 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +  const ratingInt = rating.toString().split('.')[0];
```suggestion
  const [ratingInt, ratingDecimal] = rating.toString().split('.');
```

2021-12-09 07:32 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +          <div className={`rating__border-${Math.ceil(rating / 20) * 20} rating-number-wrap me-2 d-inline`}>
I notice you do this math twice, can it be more DRY?

2021-12-09 07:32 UTC, jakxnz commented on src/js/components/RatingList/RatingList.js
> +  } = props;
Can you destructure this in the function declaration?

2021-12-09 07:32 UTC, jakxnz commented on src/js/components/RatingList/RatingList.js
> +  return (
```suggestion

  return (
```

2021-12-09 07:32 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  }
Is there a way we can do this without matching an arbitrary string?

I'm starting to think the total score shouldn't be a typical rating because we use it so differently. Could we add a hasOne record to Resorts to represent the total score maybe?

2021-12-09 07:32 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +  resort: ResortType.isRequired,
ResortImageCarousel.js
```
export const ImagesType = PropTypes.shape({
...
```

ResortCardBody.js
```
import { ImagesType } from ../ResoirtCardImageCarousel/ResortImageCarousel;

...

const ResortType = PropTypes.shape({
  ...
  resortImages: PropTypes.arrayOf(ImagesType).isRequired,
  ...
```

(Make sure to name your props using prop naming conventions)

2021-12-09 07:32 UTC, jakxnz commented on src/scss/_custom.scss
> +  &-1 {
To avoid confusion you could make these 20, 40, 60, 80, 100

2021-12-09 07:32 UTC, jakxnz commented on src/scss/components/_ratings.scss
> +.rating__ {
Would strongly recommend avoiding this. People search for `__border` when looking for sass selectors, and this is also a little harder to read.

`.rating {` would be preferred.

2021-12-09 07:32 UTC, jakxnz commented on src/scss/components/_resort-card-skeleton.scss
> +  }
I dig it.

2021-12-09 07:32 UTC, jakxnz commented on src/scss/components/_resort-card.scss
> +//Location
If your BEM naming is good, you shouldn't really need comments like this

2021-12-10 22:48 UTC, Krank3n commented on src/js/components/Rating/Rating.js
> +          <div className={`rating__border-${Math.ceil(rating / 20) * 20} rating-number-wrap me-2 d-inline`}>
I moved the math into a function:
![image](https://user-images.githubusercontent.com/45204791/145650875-6af9eda2-de31-4a22-aad8-dbdfd6d8c54e.png)
Is that a little better?

2021-12-10 23:04 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  }
Yea I think thats a good approach, I have some questions though.

Should the total score be calculated specifically to the lifestyle and what key attributes make up that lifestyle?

Should the total score be calculated from all attributes that have been scored already and exclude others?

In the meantime should the total score be just a string field completely separated from the other ratings?

2021-12-11 04:45 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  }
`     /**
      * The total score
      *
      * @return \October\Rain\Database\Relations\HasOne
      */
     public function getTotalScoreAttribute()
     {
         $ratingsWithScore = $this->ratings()
         ->where('value', '>=', 0)
         ->orderBy('value', 'desc')
         ->get();

         $totalValue = 0;

          if (count($ratingsWithScore)){
              foreach ($ratingsWithScore as $rating) {
                  $totalValue = $totalValue + $rating->value;
              }
              return round($totalValue/count($ratingsWithScore),1);
          } else {
              return $totalValue;
          }
     }`

2021-12-12 06:18 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +  }
> Should the total score be calculated specifically to the lifestyle and what key attributes make up that lifestyle?

Nah, have a different total score for that lifestyle.

> Should the total score be calculated from all attributes that have been scored already and exclude others?

Not sure. I was just planning on having a CMS-driven value until we can create a story to enhance total score(s).

> In the meantime should the total score be just a string field completely separated from the other ratings?

I haven't looked into it, but my assumption would have been we could relate a rating as a hasOne to a resort:

Resort.php
```
    public $hasOne = [
        'location' => Location::class,
        'totalScore' => Rating::class,
    ];
```

2021-12-22 03:04 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  }
But if we did it simple like this, wouldn't we rely on having to populate the total score separately instead of calculating it?

2021-12-22 03:05 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +  }
But if we did it simple like this, wouldn't we rely on having to populate the total score separately instead of calculating it?

2021-12-23 21:40 UTC, jakxnz requested changes
Really nice to be able to use this card in the browser! Great work so far man.

A responsive and collapsable component that displays the resorts:

**Collapsed:**
Title ✅
Total Score ✅
Location /Flag ✅
Subscores: ✅
*Highlights ✅
Image Carousel ❓
Expand Button ✅
Link to resort Button ✅

- The image carousel indicators are quite hard to see, do we need to make them more visible?

![image](https://user-images.githubusercontent.com/1634995/147293399-fe6b426f-01d2-4028-8fa1-f6c5bf84edad.png)

- Can we get the image filling the carousel at small mobile sizes? (It's falling short at the bottom)
![image](https://user-images.githubusercontent.com/1634995/147293520-c2b6163b-e4b2-4a32-90f2-2b6fdce93ae3.png)


- Do we care that the carousel doesn't seem to be keyboard navigable?

**Expanded:**
Title ✅
Total Score ✅
Location /Flag ✅
Subscores: ✅
*Highlights ✅
*LowLights ✅
Image Carousel ✅
Comment Carousel ❓
Collapse Button ✅
Link to resort Button ✅

- Can we avoid having the comment attribution collide with the comment carousel controls?

![image](https://user-images.githubusercontent.com/1634995/147293543-29025ebf-d0c9-42e9-b45d-4f093de8a4be.png)

- Can we get the carousel sliding with the scroll wheel?

- Did you stop using BEM naming somewhere along the line? Do you need to go through and update all your classnames to use BEM naming standards?

- Is the card support to have a fixed max-width? Or should it just expand to fill the available space?

![image](https://user-images.githubusercontent.com/1634995/147293614-8e8a6cb3-6983-4b59-b548-34e6311871fb.png)

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +    );
Could we design the error state here?

In the past we skipped the error outcome because the rest of the change set was so overwhelming, but this time around we should probably do it.

If there is an error state driven by this component, return that here. Otherwise just `throw new Error()` for our Error Boundary to pick up (when we implement error boundaries https://trello.com/c/mwiFfoAU)

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +};
Can we move these to where they are relevant?

I'm imagining trying to maintain these, looking at the code in this file, noticing it's not even there and being like "so... what is this proptype and how is it used then?" 😅

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortCardCommentCarousel/ResortCardCommetCarousel.js
> +              {`"${comment}"`}
Not a fan of HTML special chars?

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortCardHeader/ResortCardHeader.js
> +  </>
```suggestion
  <div className="rating mb-3">
    <Rating name={title} rating={rating} />
  </div>
```

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +        </span>
```suggestion
        <span>
          {`${city},`}
          &nbsp;
        </span>
        {(state && state.name) && (
          <span className="resort-header__state-name">
            {`${state.code},`}
            &nbsp;
          </span>
```

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +    <>
Are these fragments needed?

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/ResortRatings/ResortRatings.js
> +          defaultMessage="ResortRatings"
Not a fan of grammar 😆?

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
>    );
Could this just be:

```
return resorts.map(({ id, url_segment }) => (
    <ResortCard key={id} resortId={id} urlSegment={url_segment} />
);
```

?

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeleton.js
> +  <div className="resort-card__skeleton d-flex justify-content-center fade-in">
This doesn't seem like an element in the resort card block, this seems like a block itself. Hit me up for a chat about BEM naming, I might be able to help level yo skills up a bit

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeleton.js
> +          <div className="skeleton-rating-title  w-100" />
```suggestion
          <div className="skeleton-rating-title w-100" />
```

2021-12-23 21:40 UTC, jakxnz commented on src/js/components/SkeletonState/ResortCardSkeleton.js
> +          <div className="skeleton-location-details  w-50" />
```suggestion
          <div className="skeleton-location-details w-50" />
```

2021-12-23 21:40 UTC, jakxnz commented on src/js/hooks/getResortFlagImage.js
> +const getResortFlagImage = (countryCode) => (countryCode ? `https://flagcdn.com/${countryCode.toLowerCase()}.svg`
```suggestion
const useResortFlagImage = (countryCode) => (countryCode ? `https://flagcdn.com/${countryCode.toLowerCase()}.svg`
```

Hooks have the 'use' suffix

2021-12-23 21:40 UTC, jakxnz commented on src/js/hooks/getResortFlagImage.js
> +  : 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png');
Nice fallback

2021-12-23 21:40 UTC, jakxnz commented on src/js/lang/en.json
> +    "shredindex.ratinglist.NORATINGSAVAILABLE": "No Ratings Available",
```suggestion
    "shredindex.ratinglist.NO_RATINGS_AVAILABLE": "No Ratings Available",
```

2021-12-23 21:40 UTC, jakxnz commented on src/js/lang/en.json
> +    "shredindex.commentcard.NOCOMMENTSSAVAILABLE": "No Comments Available",
```suggestion
    "shredindex.commentcard.NO_COMMENTS_AVAILABLE": "No Comments Available",
```

2021-12-23 21:40 UTC, jakxnz commented on src/scss/components/_ratings.scss
> +}
> [Nitpick] Names here don't seem to match the file

➕

2021-12-23 21:40 UTC, jakxnz commented on src/scss/components/_resort-card-skeleton.scss
> +.resort-card__skeleton {
I'm confused as to why this is in its own file?

2021-12-23 21:40 UTC, jakxnz commented on src/stories/Resort/Resort.stories.js
> +      <Route exact path="resort/:urlSegment">
```suggestion
      <Route exact path="resorts/:urlSegment">
```

It's good practice to use plurals for parent segments

2021-12-23 21:40 UTC, jakxnz commented on src/stories/Resort/ResortCardSkeleton.stories.js
> +export const ResortCardSkeletonComponent = () => (
Could this be in the `ResortCard.stories.js` and toggled by a storybook control https://storybook.js.org/docs/react/essentials/controls ?

2022-01-05 22:11 UTC, Krank3n commented
> *The ![image](https://user-images.githubusercontent.com/45204791/148295443-cab0dfdb-bfd9-4b88-8c82-74c0b7f99120.png) carousel indicators are quite hard to see, do we need to make them more visible?
![image](https://user-images.githubusercontent.com/45204791/148294880-33a49952-d46e-4735-a574-28923ab75be4.png)
**Made them white with boxshadows as discussed in slack**

Can we get the image filling the carousel at small mobile sizes? (It's falling short at the bottom)
image
![image](https://user-images.githubusercontent.com/45204791/148295085-5131cd77-ba2c-44d3-a197-b2abaf6ed928.png)
**I believe I have accomplished this correctly, but may need some more testing with more images to be sure.**

Do we care that the carousel doesn't seem to be keyboard navigable?
**Good question, I guess that fails useability somewhere along the line? How important do you think it is?**

Can we avoid having the comment attribution collide with the comment carousel controls?
![image](https://user-images.githubusercontent.com/45204791/148295071-bb005c23-11d7-4342-a8a0-7ff1283115e8.png)

**I have the controls sitting just above the comment attribution for the comment carousel. and move the controls to the left for both carousels.**

Can we get the carousel sliding with the scroll wheel?
**I looked through flickety options and didn't see this as a setting, how important do you think this is?**

Did you stop using BEM naming somewhere along the line? Do you need to go through and update all your classnames to use BEM naming standards?

**Yea I'll have to do some cleanup there today**

Is the card support to have a fixed max-width? Or should it just expand to fill the available space?

I made a max width, but maybe we make it bigger. Maybe need to make a max width on the image carousel?
Heres what its like if I take the set width off and let it hit the surrounding container:
![image](https://user-images.githubusercontent.com/45204791/148296795-2dd7e145-737b-4338-90ce-a16ace31a2d4.png)

2022-01-10 20:38 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +  }
```suggestion
  const styleSuffix = Math.ceil(rating / 20) * 20;
```

2022-01-10 20:38 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +  }
```suggestion
  const isMax = ratingScore >= 100;
```

2022-02-02 20:52 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +};
Im still a bit confused on what you mean where I should be putting them. Should we have a types folder and export them and import them so they are reusable?

2022-02-03 03:30 UTC, jakxnz requested changes
Just adding some fresh comments, based on our chat

2022-02-03 03:30 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +  return (
As per our chat, could you please refactor the BEM class naming in this component?

2022-02-03 03:30 UTC, jakxnz commented on src/js/components/ResortCardHeader/ResortCardHeader.js
> +  <div className="rating mb-3">
As per our chat, could you please refactor the BEM class naming in this component?

2022-02-03 03:30 UTC, jakxnz commented on src/scss/components/_ratings.scss
> +.rating-bar-container {
As per our chat, could you please refactor the BEM class naming in this component?

2022-02-03 03:30 UTC, jakxnz commented on src/js/components/ErrorBoundary/ErrorBoundary.js
> +export default class ErrorBoundary extends React.Component {
Could you please leave this out of this PR?

2022-02-03 03:30 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +    <ErrorBoundary>
Could you please leave <ErrorBoundary> out of this PR?

2022-02-07 00:38 UTC, jakxnz requested changes
Code is looking good. I'm just focusing on the behaviour now. Have left a couple comments here, and also left you a screen recording on Slack: https://shredindex.slack.com/archives/DSUFBFUEA/p1644194207486689

2022-02-07 00:38 UTC, jakxnz commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +
```suggestion
```

2022-02-07 00:38 UTC, jakxnz commented on src/scss/components/_resort-card.scss
> +    transition-delay: $card-animation-transition-time;
👍🏻

2022-02-18 02:58 UTC, jakxnz requested changes
Not sure if this is ready for review yet, but was taking a quick look and had a question

2022-02-18 02:58 UTC, jakxnz commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
>    const flickityOptions = {
Do we need these settings in two separate places? Or could we just export a default flickity options from somewhere?

2022-02-18 02:58 UTC, jakxnz commented on src/scss/components/_flickityCarousel.scss
> +  fill: $gray-300;
❤️

2022-02-19 22:55 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
>    const flickityOptions = {
Slacked you with this:
![image](https://user-images.githubusercontent.com/45204791/154821864-85ee04a2-2edf-4659-85b8-87c04ce6e03f.png)

2022-02-27 10:29 UTC, jakxnz requested changes
It gets better and better with every round. We must be getting close. I'll let you address these minor things, and then take another practical test on the next review.

I'm also guessing that if you cover your unhappy states, you'll get that coverage report requirement passing.

2022-02-27 10:29 UTC, jakxnz commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    dataProvider.resortByUrlSegment.comments.forEach((data) => {
Do we also want to test for how the card renders when there's no comments?

2022-02-27 10:29 UTC, jakxnz commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    dataProvider.resortByUrlSegment.resort_images.forEach((data) => {
Do we also want to test for how the card renders when there's no images?

2022-02-27 10:29 UTC, jakxnz commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    dataProvider.resortByUrlSegment.lowlights.forEach((data) => {
What happens if a resort only has 3 total ratings? Are they both highlights and lowlights? What happens if a resort has no lowlights? Do we need to test for that?

2022-02-27 10:29 UTC, jakxnz commented on cypress/integration/ResortCard/ResortCard.spec.js
> +      it('Has a total rating', () => {
Do we want to test what a resort card looks like if it has no total rating?

2022-02-27 10:29 UTC, jakxnz commented on cypress/integration/ResortCard/ResortCard.spec.js
> +  context('All devices', () => {
Do we want any tests for a card's error state?

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +    <div className={`rating rating--${ratingType}`}>
Beautiful BEM class names ❤️

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +  <div className="d-flex justify-content-between">
```suggestion
  <div className="resort-card__footer d-flex justify-content-between">
```

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +    <div className="resort-card__carousel__image-wrap w-50 ms-2 mb-2">
https://www.smashingmagazine.com/2016/06/battling-bem-extended-edition-common-problems-and-how-to-avoid-them/#1-what-to-do-about-grandchild-selectors-and-beyond

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +  const flag = useResortFlagImage(countryCode);
```suggestion
  const flagImageUrl = useResortFlagImage(countryCode);
```

Pays to be declarative

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +          src={flag}
```suggestion
          src={flagImageUrl}
```

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/ResortRatings/ResortRatings.js
> +  <CCard className="resort-rating__card mb-4">
Should there be a `.resort-ratings` element somewhere?

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
>    );
Feels like there's still too much fluff here

2022-02-27 10:29 UTC, jakxnz commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +            <img key={id} className="resort-carousel-image" src={image.path} alt={alt} />
```suggestion
            <img key={id} className="carousel__image" src={image.path} alt={alt} />
```

2022-02-27 10:29 UTC, jakxnz commented on src/scss/components/_carousel.scss
> +  .resort-carousel-image {
You can kinda see how this class name stands out. If it's an element that belongs to this component, then it should be `.carousel__image` or something, or not be in this file (because it theoretically belongs to another CSS block)

2022-02-27 10:29 UTC, jakxnz commented on src/stories/Resort/ResortCard.stories.js
> +            <ResortCardComponent
Hmm, weird. I wonder why this isn't hit by our coverage report?

2022-02-27 22:25 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    it('Card Expands', () => {
Sure I'll add it in

2022-02-28 03:28 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +            <img key={id} className="resort-carousel-image" src={image.path} alt={alt} />
thanks man

2022-02-28 03:31 UTC, Krank3n commented on src/scss/components/_carousel.scss
> +  .resort-carousel-image {
Yea definitely

2022-03-01 11:43 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    dataProvider.resortByUrlSegment.comments.forEach((data) => {
Added

2022-03-01 11:43 UTC, Krank3n commented on src/stories/Resort/ResortCard.stories.js
> +            <ResortCardComponent
Unsure?

2022-03-01 11:44 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    dataProvider.resortByUrlSegment.lowlights.forEach((data) => {
Have added a test for that... hopefully its all that is needed

2022-03-01 11:46 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +    dataProvider.resortByUrlSegment.highlights.forEach((data) => {
Removed

2022-03-01 11:46 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +      it('Has a total rating', () => {
Added

2022-03-01 11:46 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +      it(`Should render highlight "${title}"`, () => {
Added Test

2022-03-01 11:47 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +  context('All devices', () => {
Not Sure?

2022-03-01 11:48 UTC, Krank3n commented on src/js/components/ResorctCardFooter/ResortCardFooter.js
> +  <div className="d-flex justify-content-between">
Added

2022-03-01 11:48 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +  <div>
Removed

2022-03-01 11:55 UTC, Krank3n commented on src/js/components/ResortCardCommentCarousel/ResortCardCommentCarousel.js
> +      <div className="resort-card__carousel__comment-wrap d-block w-50 ms-2">
Think that must of been a typo, as there was another one below with resort-card__carousel-comment-wrap

2022-03-01 12:02 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +          : <img className="resort-carousel-image" src={resortImagePlaceholder} alt="shred-index-resort-placeholder" />}
Not sure what you mean by having fallback images data?

2022-03-01 12:04 UTC, Krank3n commented on src/js/components/ResortRatings/ResortRatings.js
> +  <CCard className="resort-rating__card mb-4">
Maybe I havent looked at this. I added it in

2022-03-01 22:29 UTC, Krank3n commented on src/js/components/Resorts/Resorts.js
>    );
thanks man

2022-03-01 22:57 UTC, Krank3n commented on src/js/components/SkeletonState/ResortCardSkeleton.js
> +        </div>
Made it a component

2022-03-01 22:59 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +          : <img className="resort-carousel-image" src={resortImagePlaceholder} alt="shred-index-resort-placeholder" />}
Just tested this again and the div was redundant, so have removed it.

2022-03-03 01:03 UTC, jakxnz requested changes
Getting down to the nitpicks now (and one must-have question).

- What's the different between "Minimal data" and "No data"?

![image](https://user-images.githubusercontent.com/1634995/156475178-67fe92ce-186b-4f94-bc81-24f7cbcbc47d.png)
![image](https://user-images.githubusercontent.com/1634995/156475188-7146e2bc-7bdb-4504-a992-c46d967b5daa.png)

- Why is it that when there's less space, we get more image carousel, but when there's more space we get less image caoursel?

![image](https://user-images.githubusercontent.com/1634995/156475417-db55301d-45be-4e13-a12a-385a1b277f3f.png)
![image](https://user-images.githubusercontent.com/1634995/156475433-393fb950-3348-4040-8b65-0787a40a64ce.png)

- Are you gonna turn off carousel swipe controls for desktop? Or is that too difficult?

- I notice the new desktop controls don't come up when I hover. Am I supposed to be psychic 😅?

- One of the must-haves are identified was that any interaction with the card does something, but I don't see any interactivity in the Title, Description, Ratings etc. We spoke recently about those linking somewhere, are you still going to add this?

2022-03-03 01:03 UTC, jakxnz commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        {images.length > 0 ? images.map(({ id, alt, image }) => (
I don't see any markup that suggests these images go anywhere when I interact with them directly e.g I click on them. Can we make sure they link somewhere?

2022-03-03 01:03 UTC, jakxnz commented on src/js/components/ResortCardCommentCarousel/ResortCardCommentCarousel.js
> +          <div key={id} className="carousel__comment w-100 d-flex flex-column justify-content-between">
I don't see any markup that suggests these comments go anywhere when I interact with them directly e.g I click on them. Can we make sure they link somewhere?

2022-03-03 01:45 UTC, Krank3n commented
> 



> Getting down to the nitpicks now (and one must-have question).
> 
> * What's the different between "Minimal data" and "No data"?
Did you try refreshing?
> 
> ![image](https://user-images.githubusercontent.com/1634995/156475178-67fe92ce-186b-4f94-bc81-24f7cbcbc47d.png) ![image](https://user-images.githubusercontent.com/1634995/156475188-7146e2bc-7bdb-4504-a992-c46d967b5daa.png)
> 
> * Why is it that when there's less space, we get more image carousel, but when there's more space we get less image caoursel?

I did experience this initially, but fixed it, not sure why you are experiencing it.
> 
> ![image](https://user-images.githubusercontent.com/1634995/156475417-db55301d-45be-4e13-a12a-385a1b277f3f.png) ![image](https://user-images.githubusercontent.com/1634995/156475433-393fb950-3348-4040-8b65-0787a40a64ce.png)
> 
> * Are you gonna turn off carousel swipe controls for desktop? Or is that too difficult?
I didn't plan on it. I like it :) Do we need to?

> * I notice the new desktop controls don't come up when I hover. Am I supposed to be psychic 😅?
Really??? they are working for me?
> * One of the must-haves are identified was that any interaction with the card does something, but I don't see any interactivity in the Title, Description, Ratings etc. We spoke recently about those linking somewhere, are you still going to add this?
Hmmm the router isn't working at all though at the moment?

2022-03-03 02:17 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +        cy.get('.card.collapsed').should('exist');
Not really, Are you able to help give me a direction please?

2022-03-03 02:18 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +        cy.get('span').next().next().should('contain.text', 'Japan');
cy.get('.resort-card__location-title').should('exist) ?

2022-03-03 02:21 UTC, Krank3n commented on src/js/components/ResortCardLocation/ResortCardLocation.js
> +            <FormattedMessage id="shredindex.resort.NO_LOCATION_AVAILABLE" defaultMessage="No Location Available" />
Yea sorry, i updated the en file but forgot to update this

2022-03-03 02:22 UTC, Krank3n commented on src/js/components/ResortCardCommentCarousel/ResortCardCommentCarousel.js
> +              defaultMessage="No Comments Available"
Resort Has No Comments

2022-03-03 02:49 UTC, Krank3n commented on src/js/components/RatingList/RatingList.js
> +        <FormattedMessage id="shredindex.ratinglist.RESORT_IS_UNRATED" defaultMessage="Resort Is Unrated" />
I googled this titular grammer still didnt make sense of it? Is it when you making an over bearing statement?

2022-03-03 02:50 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +    );
Yea,,, I need to get slippery smooth
 like JD

2022-03-03 02:52 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +}
hmmmm i need to remember this one... lock in it tommy

2022-03-03 02:58 UTC, Krank3n commented on src/js/components/ResortCardBody/ResortCardBody.js
> +  </>
haha got that from the before comment :)

2022-03-03 03:00 UTC, Krank3n commented on src/js/components/ResortCardCommentCarousel/ResortCardCommentCarousel.js
> +    <div className="resort-card__carousel-comment-wrap d-block w-50 ms-2 border-radius-medium">
Changed this, also the same in image carousel

2022-03-03 03:01 UTC, Krank3n commented on src/js/components/ResortCardHeader/ResortCardHeader.js
> +  const score = totalScore ? totalScore.value : 'n/a';
Dude, tricky question. Google didnt give a me a straight answer, nut I guess it isn't as in japan its: 該当なし
Gaitō nashi

2022-03-03 03:04 UTC, Krank3n commented on src/js/components/ResortCardHeader/ResortCardHeader.js
> +  const score = totalScore ? totalScore.value : 'n/a';
But do we want to be displaying different abreviations here?... Gaitō nashi is too big to fit. Is there an international/univeral alternative? an Icon or :( could work?

2022-03-03 03:05 UTC, Krank3n commented on src/js/components/ResortRatings/ResortRatings.js
> +                %
This isnt part of the resort card... but I'll add it in.

2022-03-03 03:20 UTC, Krank3n commented on src/scss/components/_rating.scss
> +      border-color: var(--cui-rating-20);
Hmmm not sure why that is, I thought it there was there for a reason... maybe because variables hadn't been made for them yet.

2022-03-03 03:20 UTC, Krank3n commented on src/stories/Resort/ResortCard.stories.js
> +    return (<ResortCardSkeleton />);
lmao

2022-03-03 03:35 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        {images.length > 0 ? images.map(({ id, alt, image }) => (
Where do you want them to go? Are you thinking resortPage->image section?

2022-03-03 03:36 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        {images.length > 0 ? images.map(({ id, alt, image }) => (
Are you just after a <a> tag wrap with an href="#" in the meantime?

2022-03-03 03:54 UTC, Krank3n commented on src/js/components/ResortCardImageCarousel/ResortImageCarousel.js
> +        {images.length > 0 ? images.map(({ id, alt, image }) => (
Jackson Added new Trello Task :)

2022-03-03 04:14 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +        cy.get('.card.collapsed').should('exist');
`  it('Card Collapses', () => {
    cy.get('.card').then(($card) => {
      cy.get('.card.collapsed').should('exist');
      cy.get('.resort-card__expand').click();
      cy.get('.card.collapsed').should('not.exist');
      cy.get('.resort-card__expand').click();
      cy.get('.card.collapsed').should('exist');
    });
  });`

2022-03-03 04:45 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +        cy.get('.card.full-expanded').should('exist');
took out the conditional part

2022-03-03 05:39 UTC, Krank3n commented on cypress/integration/ResortCard/ResortCard.spec.js
> +        .contains(`${title}`).next()
Not sure how you would do this instead... it uses the first div as a reference point that contains the title

2022-03-03 06:26 UTC, jakxnz requested changes

2022-03-03 06:26 UTC, jakxnz commented on src/js/components/Rating/Rating.js
> +      </span>
```suggestion
      <h3 className="rating__title display-5 text-left mb-2 user-select-none" color="secondary">
        {title}
      </h3>
```

It would help our SEO if we use HTML semantically https://www.thoughtco.com/why-use-semantic-html-3468271

2022-03-03 06:37 UTC, jakxnz commented on cypress/integration/ResortCard/ResortCard.spec.js
> +        .contains(`${title}`).next()
I think the more declarative version of this would be...

```
cy.get('.rating__title').contains(`${title}`)
  .next('.rating__bar-container')
  .find('.rating__bar')
  .should('have.attr', 'style', `width: ${value}%;`);
```

I don't need to know the markup to understand what's going on there.

2022-03-03 06:40 UTC, Krank3n commented on src/js/components/Rating/Rating.js
> +      </span>
Yea makes sense... but are these titles?

2022-03-04 10:03 UTC, jakxnz commented on src/js/components/ResortCardHeader/ResortCardHeader.js
> +  const score = totalScore ? totalScore.value : 'n/a';
It's good enough for MVP2 I reckon!

2022-03-04 10:10 UTC, jakxnz approved these changes
Holy shit. Hoooly mother fuckin' shitballs man. Dis is dat super dope jungle massive shit yeah?

...

...

...

LGTM!!!!

![Green](https://tenor.com/view/go-green-cool-swag-dance-gif-12671410)

2022-03-04 22:21 UTC, Krank3n reviewed
Looks good :)

2022-03-04 22:42 UTC, merged