Ranked Resort List
underflip/shredindex-frontend pull request #43
Opened 2022-03-24 08:12 UTC by Krank3n

A list of the resort cards, with working pagination.

https://trello.com/c/fmQKZee3/11-ranked-resorts-component

I can see a list of resorts
I can see resorts displayed in "pages"
I can change the current page of resorts
When I revisit the URL of a specific page, I see that same page of resorts
When I click a resort, I'm taken to that resorts booking page on their website
When I click "Go to resort", I'm taking to the resort's page on our website
I can tell when something has gone wrong with resort fetching, without breaking my ability to navigate the website
I can understand clearly where and how to filter the resorts I can see

2022-03-25 08:03 UTC, jakxnz requested changes
Great feature man. Your React game is coming a long way. I've picked up everything I noticed on my first pass.

2022-03-25 08:03 UTC, jakxnz commented on src/js/components/ResortRatings/ResortRatings.js~ranked-resorts-component
> +import React from 'react';
I'm guess this file was for your own reference and doesn't need to be in the PR?

2022-03-25 08:03 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +  <>
So where is the `resorts` element then?

2022-03-25 08:03 UTC, jakxnz commented on src/js/components/Pagination/Pagination.js
> +  size,
Are we ever going to use more than 1 size?

2022-03-26 00:00 UTC, Krank3n commented on src/js/components/FilterResorts/FilterResorts.js
> +    <CButton color="dark" className="m-2">Filters</CButton>
I'd say the one where we do the filterComponent UI?

2022-03-26 00:05 UTC, Krank3n commented on src/js/components/FilterResorts/FilterResorts.js
> +    <CButton color="primary" className="m-2">LifeStyles</CButton>
Took me 3 rereads to see what the difference was...

2022-03-26 00:42 UTC, jakxnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ranked resorts component](https://trello.com/c/fmQKZee3/11-ranked-resorts-component)

2022-03-26 04:11 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +          ))}
ooo cool thanks for this dude... I thought there must of been a better way than creating an array from scratch then using it.

2022-03-26 04:15 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +    <>
added

2022-03-26 04:16 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +      <>
added

2022-03-26 04:20 UTC, Krank3n commented on src/js/components/FilterResorts/FilterResorts.js
> +const FilterResorts = () => (
Hmmm could call it getLaid

2022-03-26 04:21 UTC, Krank3n commented on src/js/components/RatingList/RatingList.js
> +      <CLink className="resort-card__affiliate-link link-unstyled" href={affiliate_url}>
done

2022-03-26 04:22 UTC, Krank3n commented on src/js/components/RatingList/RatingList.js
> +            .map(({ id, title, value }) => (
coolp

2022-03-26 04:22 UTC, Krank3n commented on src/js/components/RatingList/RatingList.js
> +  ratings, label, labelMessageId, affiliate_url,
ehhhh soz

2022-03-26 04:25 UTC, Krank3n commented on src/js/components/Resorts/Resorts.js
> +  <>
thanks dude

2022-03-26 04:26 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  size,
Yea quite possibly. Large looks way better on desktop, and small fits well on mobile. I should add this actually

2022-03-26 04:47 UTC, Krank3n commented on src/js/components/ResortRatings/ResortRatings.js~ranked-resorts-component
> +import React from 'react';
Hmmm Im not sure on this. This component is used in the Resort.js component. I don't see it in my changes in history for this... which I am puzzled about. Maybe it was with merge conflicts
![image](https://user-images.githubusercontent.com/45204791/160225083-9161fd7f-b9e5-43d5-a063-1dbeedb65088.png)

2022-03-26 04:48 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  const showPageList = () => {
very true... thanks for that.

2022-03-26 07:02 UTC, jakxnz commented on src/js/components/ResortRatings/ResortRatings.js~ranked-resorts-component
> +import React from 'react';
Yeah... Why would the filename be `ResortRatings.js~ranked-resorts-component` 😅?

2022-03-26 07:06 UTC, jakxnz commented on src/js/components/FilterResorts/FilterResorts.js
> +    <CButton color="dark" className="m-2">Filters</CButton>
Alright. Typically I find when a component is 1/2 implemented, the next change set "not my problem" 😅. So let's make a point of spelling that out in the filter UI ACs

2022-03-26 08:55 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  );
Man this took some time :)

2022-03-26 08:59 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  currentPage,
Hmm true

2022-03-26 08:59 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +      {showPageList().map((number) => (
Hopefully the new work is a bit cleaner

2022-03-26 08:59 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  }
I liked this

2022-03-27 06:46 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +  const lastPageStore = 10;
added

2022-03-27 09:45 UTC, jakxnz requested changes
Nice improvements. A few more nitpicks from me.

Practical tests:

**ACs:**

**I can see a list of resorts** 🟠

Localhost is working:
![image](https://user-images.githubusercontent.com/1634995/160275912-43a75402-0cb9-44d9-8514-b649b8849d22.png)

Storybook appears to have broken images
![image](https://user-images.githubusercontent.com/1634995/160275341-52f2aec7-e13e-48dd-b0bf-f38423c2b2bb.png)


**I can see resorts displayed in "pages"** 🟢

![image](https://user-images.githubusercontent.com/1634995/160275773-be4eac11-c23c-4a60-95a1-a467859e9691.png)

**I can change the current page of resorts** 🟠

I've sent you a screen recording on Slack with my experience.

**When I revisit the URL of a specific page, I see that same page of resorts** 🟢

![image](https://user-images.githubusercontent.com/1634995/160275803-9ffec19f-85f3-46bd-8e16-d836128b804a.png)

**When I click a resort, I'm taken to that resorts booking page on their website** 🟠 

![image](https://user-images.githubusercontent.com/1634995/160275821-41f7d242-e94d-44a9-91c2-7fcf4a04e80e.png)

Working but I have one PR question on this.

**When I click "Go to resort", I'm taking to the resort's page on our website** 🔴 

_Technically_ the URL changes, but the page is broken.

![image](https://user-images.githubusercontent.com/1634995/160275946-bc31f009-1504-4be5-ac74-4e4c70d6869f.png)

**I can tell when something has gone wrong with resort fetching, without breaking my ability to navigate the website**  🟢

![image](https://user-images.githubusercontent.com/1634995/160275857-f92ada32-cfef-489d-b5d7-d2b93221974a.png)

**I can understand clearly where and how to filter the resorts I can see** 🟠

![image](https://user-images.githubusercontent.com/1634995/160275871-e174c8a1-9c36-4cae-9cf7-86aef45ebe07.png)

I wouldn't necessarily call this clearly. The Filters button is pretty easy to ignore.

**Minor enhancements:**

- Do we want to indicate which page we're on of how many (and how many results in total)
![image](https://user-images.githubusercontent.com/1634995/160275624-fe368b9b-e4fe-4435-8069-3ad43cf4cce4.png)

- Do we want to give the user some actions to follow when they see the error screen? (Like going back to the home screen)
![image](https://user-images.githubusercontent.com/1634995/160275740-670c18de-4e42-4187-87ee-3fba50d4b839.png)

- Do we want to raise a story on the board to fully implement these error screens?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/Pagination/Pagination.js
> +  }
```suggestion
  const elipsis = {
    name: '...',
    ariaLabel: '...',
    disabled: true,
    setPageTo: null,
  };

  // Left hand pagination controls
  const receding = [
    {
      name: '«',
      ariaLabel: 'First',
      disabled: currentPageIndex === 1,
      setPageTo: 1,
    },
    {
      name: '‹',
      ariaLabel: 'Previous',
      disabled: currentPageIndex === 1,
      setPageTo: currentPage-1,
    },
  ];
  
  if (Math.min(...pageSeq) > 1) {
    // Indication that the pagination is off the floor
    receding.push(elipsis);
  }
  
  // Right hand pagination controls
  const proceeding = [
    {
      name: '›',
      ariaLabel: 'Next',
      disabled: lastPage === currentPageIndex,
      setPageTo: currentPageIndex+1,
    },
    {
      name: '»',
      ariaLabel: 'Last',
      disabled: lastPage === currentPageIndex,
      setPageTo: lastPage,
    },
  ];
  
  if (Math.max(...pageSeq) < lastPage) {
    // Indication that the pagination hasn't reached the ceiling
    proceeding.unshift(elipsis);
  }

  // Combined pagination controls
  const paginationData = [
      ...receding,
      ...pageSeq.map((x) => ({
        name: x,
        ariaLabel: x,
        active: currentPageIndex === x,
        setPageTo: x,
      }),
      ...proceeding
  ];
```

Not a single `.splice` nor assumption about how many pages there are in the displayed sequence needed 😉

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +  );
You gonna address this?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +      <>
If this was added, I would expect to see `<div class="ranked-resort-list ranked-resort-list--loading">` here (or something to that effect)

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +    <>
Is it?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +        size="lg"
You mentioned that mobile would use `sm` and desktop would use `lg`. Where the mobile implementation?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/ResortRatings/ResortRatings.js~ranked-resorts-component
> +import React from 'react';
Is this yet to be addressed?

2022-03-27 09:45 UTC, jakxnz commented on src/js/hooks/useQueryResorts.js
> +
Where is the hook function?

2022-03-27 09:45 UTC, jakxnz commented on src/stories/coreui/Pagination.stories.js
> +      <MockedProvider addTypename={false}>
If there are no mocks, is this needed?

2022-03-27 09:45 UTC, jakxnz commented on src/images/RankedResortsBackground.svg
> +</linearGradient>
Any chance we could parallax some of these as we scroll? Something really subtle, just enough to create depth and playfulness but not be distracting.

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/RatingList/RatingList.js
> +      <CLink className="resort-card__affiliate-link link-unstyled" rel="noreferrer noopener" href={affiliateUrl}>
Do we want outbound links to open in a new tab?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/ResortCard/ResortCard.js
> +          <CLink className="resort-card__affiliate-link link-unstyled" rel="noreferrer noopener" href={affiliate_url}>
Do we want outbound links to open in a new tab?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +          <CLink className="resort-card__affiliate-link link-unstyled" rel="noreferrer noopener" href={affiliate_url}>
Do we want outbound links to open in a new tab?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/ResortCardBody/ResortCardBody.js
> +            <CLink className="resort-card__affiliate-link link-unstyled" rel="noreferrer noopener" href={affiliate_url}>
Do we want outbound links to open in a new tab?

2022-03-27 09:45 UTC, jakxnz commented on src/js/components/ResortCardError/ResortCardError.js
> +                <p className="fs-6 fw-lighter text-break">{stack}</p>
Our frontend users don't need to see the specifics. People use this information to hack your platform. Try and give the user as much detail as they need to choose their next action, without exposing anything under the hood.

2022-03-29 02:45 UTC, Krank3n commented on src/js/components/ResortRatings/ResortRatings.js~ranked-resorts-component
> +import React from 'react';
No it wasnt... I addresseed it now

2022-03-29 02:50 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  )), lastPage - paginationTabLimit + 1);
Yea it is a bit

2022-03-29 03:05 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  }
Nice find, thanks mate

2022-03-29 21:48 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  }
I like alot about this... calling it ellipsis, then doing it in sections. I actually kinda had it that way in my head initially, but didn't think to actually do it like this. Thanks for this man, really helpful!

2022-03-29 21:59 UTC, Krank3n commented on src/js/components/ResortCard/ResortCard.js
> +          <CLink className="resort-card__affiliate-link link-unstyled" rel="noreferrer noopener" href={affiliate_url}>
Hmmm good point

2022-04-10 04:43 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +  );
added and works this time round

2022-04-10 04:44 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +    <>
no it wasnt... I

2022-04-10 04:45 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +      <>
exactly sorry mate, missed it

2022-04-10 04:50 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +    paginationData.splice(2 + index, 0, {
thanks mate

2022-04-10 05:22 UTC, Krank3n commented on src/stories/coreui/Pagination.stories.js
> +      <MockedProvider addTypename={false}>
I have taken this out :)

2022-04-10 05:37 UTC, Krank3n commented on src/js/components/RatingList/RatingList.js
> +      <CLink className="resort-card__affiliate-link link-unstyled" rel="noreferrer noopener" href={affiliateUrl}>
Probably

2022-04-10 05:37 UTC, Krank3n commented on src/images/RankedResortsBackground.svg
> +</linearGradient>
Hmmm I have tried this out... I feel like It's a bit laggy this way. May need to do an alternative.

2022-04-10 05:38 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        size="lg"
Added in another hook to get the dimensions.

2022-04-10 05:48 UTC, Krank3n commented on src/images/RankedResortsBackground.svg
> +</linearGradient>
I notice it lag when the resort images are loading, but not with the skeleton list. WOuld be good if you get a change to take a look :)

2022-04-12 04:40 UTC, jakxnz requested changes
Yeah man, this is getting good! I have a few more nitpicks, and notices some small things in the new code, but glad to see the improvements since the last round. Nice work.

Practical tests:

**ACs:**

**I can see a list of resorts** 🟢

Localhost is working:
![image](https://user-images.githubusercontent.com/1634995/160275912-43a75402-0cb9-44d9-8514-b649b8849d22.png)
![image](https://user-images.githubusercontent.com/1634995/162879345-37f1385d-c5a7-4765-9468-832561d1d80f.png)

**I can see resorts displayed in "pages"** 🟢

![image](https://user-images.githubusercontent.com/1634995/160275773-be4eac11-c23c-4a60-95a1-a467859e9691.png)

**I can change the current page of resorts** 🟠

I'm still noticing some funny business with the paginator. Have sent you a video on slack https://shredindex.slack.com/archives/DSUFBFUEA/p1649737504969639

**When I revisit the URL of a specific page, I see that same page of resorts** 🟢

![image](https://user-images.githubusercontent.com/1634995/160275803-9ffec19f-85f3-46bd-8e16-d836128b804a.png)

**When I click a resort, I'm taken to that resort's booking page on their website** 🟢

**When I click "Go to resort", I'm taking to the resort's page on our website** 🟢

![image](https://user-images.githubusercontent.com/1634995/162880932-1d7a982c-720e-4e70-8da6-89cdc61ed617.png)

**I can tell when something has gone wrong with resort fetching, without breaking my ability to navigate the website**  🟢

![image](https://user-images.githubusercontent.com/1634995/162881355-1dd68c74-bd91-4f61-b1ca-97181831f428.png)

**I can understand clearly where and how to filter the resorts I can see** 🟠

What's going on with the responsive view?
![image](https://user-images.githubusercontent.com/1634995/162881680-78cb2b0a-76e4-4c39-ad94-7048a097a4f0.png)

**Minor enhancements:**

- **Do we want to indicate which page we're on of how many (and how many results in total)** 🟢

- **Do we want to give the user some actions to follow when they see the error screen? (Like going back to the home screen)** 🟢

- **Do we want to raise a story on the board to fully implement these error screens?** ❓

I'm unsure if this has been done.

- **Can we address the prop type errors in the console?**

I'm guessing these are just due to a need for fallbacks/redundancies/sanity-checks.

```
Warning: Failed prop type: The prop `totalScore.title` is marked as required in `ResortCardHeader`, but its value is `undefined`.
```

```
Warning: Failed prop type: ResortCardBody: prop type `resort.resort_images[0].image` is invalid; it must be a function, usually from the `prop-types` package, but received `object`.
```

```
Warning: Failed prop type: ResortImageCarousel: prop type `images[0].image` is invalid; it must be a function, usually from the `prop-types` package, but received `object`.
```

![image](https://user-images.githubusercontent.com/1634995/162881911-83065fe2-730b-4049-88f4-eea69dbe8a82.png)

2022-04-12 04:40 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +        </div>
You _kinda_ have the right idea. This is quite an intense way to pull it off.

The reason this isn't smooth is that you're using React's lifecycle to run your animation. Not only will this result in only updating when React re-renders your component, but the overhead is quite intense (and there's quite a bit of bloat added by this markup to the `Resort` component.)

My suggestion:

Make a `ResortsParallaxBackground` component. Inside that component, return your SVG data. Your SVG data has `id`s on all the elements you want to select and move on the page, so also in that component file just bind an event listener to the scroll event, and move those svg elements accordingly. You can even add some easing to make is smoother for clicky scroll wheels. I guess is you won't need more than svg markup and some simple event handler logic.

2022-04-12 04:40 UTC, jakxnz commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
Does this need to `useState`? Or is that just overkill when you could just get the values from `window` everytime?

2022-04-18 01:55 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +  };
getPageNumber ok?

2022-04-18 02:06 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        <div className="d-flex flex-column">
sure

2022-04-24 01:56 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +  };
Or you could just:

```
const { loading, data, error } = useQueryResorts(cardLimit, Number(num) || 1);
```

2022-04-24 04:20 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +          size={width > 590 ? 'lg' : 'sm'}
For the lg and sm string, are you talking along the lines of an enum, or using in proptypes.OneOfType? Or something else?

2022-04-25 06:40 UTC, Krank3n commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
hmmm I couldnt get this working with just using window. Does it really slow it down?

2022-04-25 08:27 UTC, jakxnz requested changes
The logic is all pretty sound, and the feature is very nice to use. I've just added some questions around things I noticed. Some of them are nitpicks. I'm confident addressing these questions will get it over the line! Nice work so far.

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
Why is there a FootNav component in the scope of this PR, btw? Did it get moved or something?

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +      <>
Why is the pagination outside of the `ranked-resort-list` element while loading, but inside the `ranked-resort-list` element once loaded? Shouldn't the loading markup match the loaded markup?

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +        <Pagination
Any word on this?

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +  const [maxPageState] = useState({ key: '', maxPages: 0 });
It has since occurred to me that this could probably use a `useRef`

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +        <div className="ranked-resort-list ranked-resort-list--loading col-sm-12">
Do we want the loading skeleton to also include structures for the filter menu and result count?

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/Resort/Resort.js
> +  console.log('query resort', url_segment);
```suggestion
  const { url_segment } = useParams();
```

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/Resorts/Resorts.js
> +      <RankedResortList cardLimit={5} maxPages={10} />
What does the `maxPages` here do?

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/ResortsParallaxBackground/ResortsParallaxBackground.js
> +  bgImages.forEach((image) => {
Does this really need to be multiple images? Could you just select elements within the SVG markup and just have one `.svg`?

2022-04-25 08:27 UTC, jakxnz commented on src/js/components/SecondaryHeader/SecondaryHeader.js
> +const SecondaryHeader = () => {
SecondaryHeader was removed in the routing feature. Is there a reason it's back?

2022-04-25 08:27 UTC, jakxnz commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
Not sure man, you built it. I'm guessing the reason this uses `useState` is so that it triggers a re-render when the window values change?

2022-04-25 08:27 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +    it('Should be able to navigate page', () => {
Can we cover all the use cases for the paginator somewhere? i.e Previous, Next, Clicking a number, Reaching the start, Reaching the end. You know... all that sexy logic you wrote.

2022-04-25 08:27 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +      data: [
Why so much data for a handful of small tests? Is all this data going to be a headache for us to maintain down the line? Does it need to be so bloated? Is there a way to make it more manageable, or perhaps only include data you're actually testing?

For example, could there be a helper function that generates a resort's data (with some variability), and we can just tweak a single function rather than dumpster dive 1,500 lines of code?

2022-04-25 08:27 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +    it('Pagination should be showing an active page', () => {
Should pagination tests be in the `RankedResortList.spec.js` or in something more like `Pagination.spec.js`?

2022-04-25 21:36 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +          size={width > 590 ? 'lg' : 'sm'}
Everywhere where there is an arbitrary string, e.g `'lg'`, use a reference instead. i.e

`Pagination.js`:
```
export sizes = {
  sm: 'sm',
  lg: 'lg',
}
```

Usage:
```
import sizes from 'Pagination.js';

...
  <Pagination
    ...
    sizes={sizes.lg}
```

You can use the same references for a `propTypes.oneOfType()`, yeah.

2022-04-25 22:53 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        <Pagination
Oh sorry, I missed this. I went over it because I wasn't quite sure what you meant by making it read only. I know there is the collapse expand functionality still in it. DO you mean just removing that?

Or there a specific way to make the component read only?

2022-04-25 22:57 UTC, Krank3n commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
Hmmm yes that is questionable... I merged 'develop' into this branch, which had this file. It shouldn't be any different to whats on develop. I cant even see it in the Merge differences??

2022-04-25 23:09 UTC, Krank3n commented on src/js/components/SecondaryHeader/SecondaryHeader.js
> +const SecondaryHeader = () => {
I'll have to delete it manually.

2022-04-25 23:13 UTC, Krank3n commented on src/js/components/ResortsParallaxBackground/ResortsParallaxBackground.js
> +  bgImages.forEach((image) => {
Hmmm good question. I struggled to able the control the SVG there ID's, as with react component 'CImage' it didn't render the SVG code in the HTML. I tried just using the SVG's without CImage, and I couldn't get them to render at all.

2022-04-25 23:19 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
Exactly, so there shouldn't be a diff of this file in it on your branch, if the code on the branch you're merging into is exactly the same.

2022-04-25 23:20 UTC, jakxnz commented on src/js/components/ResortsParallaxBackground/ResortsParallaxBackground.js
> +  bgImages.forEach((image) => {
SVG is just markup, so there shouldn't be a technical reason why you can get it into the DOM?

2022-04-26 03:18 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +        <Pagination
Nah there isn't, Read only basically just means you can see it but you can't alter it. I.e you can see the paginator, but you can't interact with it.

2022-04-26 03:26 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
Yeah, not sure. It probably came up during merging. Rebasing usually avoids stuff like this. Maybe try `git checkout origin/develop src/js/components/FooterNav/FooterNav.js` and see if that removes the diff?

2022-04-30 10:53 UTC, Krank3n commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
Hmmm that didnt work...

2022-04-30 10:55 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        <div className="ranked-resort-list ranked-resort-list--loading col-sm-12">
I thought I replied to this already.... I think that the loading skeleton for the filter menu should be applied when we do the menu no? As the design has changed already.

2022-04-30 11:04 UTC, Krank3n commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
Wouldnt that be a good thing?

2022-05-01 08:52 UTC, jakxnz commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
Right. FooterNav doesn't exist anymore (it's called `FooterMainMenu` now). So you can delete this from your branch.

2022-05-01 09:06 UTC, jakxnz requested changes
Just fine tuning at this point. I haven't got any new change requests, just following up on existing ones.

I'm still seeing console errors on the Resorts page, e.g

```
Warning: Failed prop type: The prop `totalScore.title` is marked as required in `ResortCardHeader`, but its value is `undefined`.
```

There's usually 3 different ones.

![image](https://user-images.githubusercontent.com/1634995/166139185-b7a15560-a9c8-4312-9d90-c016295d2620.png)

Seems like I might be doing a PR before you've addressed all the items in my last round. I'll save a practical test until they're all covered.

2022-05-01 09:06 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +      data: [
Any word on this?

2022-05-01 09:06 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +    it('Pagination should be showing an active page', () => {
Any word on this?

2022-05-01 09:06 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +    it('Should be able to navigate page', () => {
Any word on this?

2022-05-02 06:01 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        <div className="ranked-resort-list ranked-resort-list--loading col-sm-12">
I have added it this time around

2022-05-02 06:32 UTC, Krank3n commented on src/js/components/FooterNav/FooterNav.js
> +const FooterNav = () => (
cool

2022-05-02 10:39 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        <Pagination
Firstly are you talking about the paginator or skeleton of the resortCard?

Secondly I couldn't replicate strange behavior with either of them.

Thirdly I did try to pass the loading state to the pagination just to possibly enhance any possible user errors, however the pagination doest receive the loading prop until after it's loaded. Im sure there's a work around for this, but am unsure of it?

2022-05-02 10:46 UTC, Krank3n commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
I used useState to update the width and length size on window size change. Is there a way you recommend to get the window width and height and update the state when it changes as opposed to on load?

2022-05-02 11:01 UTC, Krank3n commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +    it('Should be able to navigate page', () => {
Sorry I missed this one... let me add some more tests in...

2022-05-02 11:03 UTC, Krank3n commented on src/js/components/RankedResortList/RankedResortList.js
> +        <div className="ranked-resort-list ranked-resort-list--loading col-sm-12">
hmmm i left one in the loading. Removed

2022-05-05 08:49 UTC, jakxnz requested changes
Keep the good improvements coming my man! Will do a full practice test on the next one.

2022-05-05 08:49 UTC, jakxnz commented on cypress/integration/Pagination/Pagination.spec.js
> +    it('Should be able to navigate a page', () => {
Can we assert something to prove that this passes/fails?

2022-05-05 08:49 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +      data: [
Makes me wonder if our dummy resorts should be in their own file, e.g `cypress /integration/RankedResortList/dummyResortOne.js` and then they don't need to be in this test file, and can be easier to compare side by side when the data structure changes down the line and we need to apply updates. What do you think?

2022-05-05 08:49 UTC, jakxnz commented on cypress/integration/RankedResortList/RankedResortList.spec.js
> +    it('Pagination should be showing an active page', () => {
Do these paginator related test steps still need to be here, if you've created the other `.spec.js`?

2022-05-05 08:49 UTC, jakxnz commented on src/js/components/RankedResortList/RankedResortList.js
> +        <Pagination
The paginator.

I'll send you a video on Slack.

I'm not sure what this thirdly means, I'll hit you up on Slack to clarify.

2022-05-05 08:49 UTC, jakxnz commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
I first wanted to understand what the rationale of this solution is because maybe I'm missing something. So sorry if these suggestions are off base:

Do we want to just use a responsive package for our responsive logic? https://www.npmjs.com/package/react-responsive

If not, does a solution like we what have here (that appears like it re-renders on every pixel-width change of the browser) need something like a debounce to avoid over-processing? https://www.pluralsight.com/guides/re-render-react-component-on-window-resize

2022-05-09 09:13 UTC, jakxnz commented on src/js/components/Pagination/Pagination.js
> +  }
Hmm, you might be re-introducing your old assumption that there are only ever 3 items in the paginator.

```
const floor = Math.min(
    Math.max(
      1,
      currentPageIndex - Math.floor(paginationTabLimit / 2),
    ),
    Math.max(
      1,
      lastPage - paginationTabLimit + 1,
    ),
  );
```

Will that achieve the same thing? (Will it make sure the floor is never less than 1?)

2022-05-09 09:15 UTC, jakxnz commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
Were there any changes here?

2022-05-09 09:15 UTC, jakxnz commented on cypress/integration/Pagination/Pagination.spec.js
> +    it('Should be able to navigate a page', () => {
Any word on this?

2022-05-09 09:17 UTC, jakxnz commented on src/stories/Resort/RankedResortsList.stories.js
> +import RankedResortsListComponent from '../../js/components/RankedResortList/RankedResortList';
Just noticed that everything in this file, including the name of the file, is called `RankedResortsList`, but the component is called `RankedResortList` (no plural on `Resort`)

2022-05-09 10:40 UTC, Krank3n commented on cypress/integration/Pagination/Pagination.spec.js
> +    it('Should be able to navigate a page', () => {
Ohhh I wasnt sure on what you meant, but I think I get it now. You want to clarify in the test that it actually proves something other than clicking the next page? Let me update it.

2022-05-09 10:59 UTC, Krank3n commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
Sorry I missed this.

Im good with either option. Is there one you would prefer?
Woud using the package file become be heavier?

2022-05-09 11:04 UTC, Krank3n commented on cypress/integration/Pagination/Pagination.spec.js
> +    it('Should be able to navigate a page', () => {
I just added in a check to make sure it is on the next page.

2022-05-09 11:12 UTC, Krank3n commented on src/js/components/Pagination/Pagination.js
> +  }
Yea it works well :)

2022-05-09 11:17 UTC, Krank3n commented on src/js/hooks/getWindowDimensions.js
> +  const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions());
I added a debounce, Im not quite sure which would be better, the package does look useful, but maybe its extra we don't need?

2022-05-09 11:22 UTC, Krank3n commented on src/stories/Resort/RankedResortsList.stories.js
> +import RankedResortsListComponent from '../../js/components/RankedResortList/RankedResortList';
fixed

2022-05-09 11:22 UTC, Krank3n commented on src/stories/Resort/RankedResortsList.stories.js
> +import RankedResortsListComponent from '../../js/components/RankedResortList/RankedResortList';
nice find

2022-05-09 11:33 UTC, Krank3n commented on src/js/types/types.js
> +  title: string,
Added back

2022-05-22 09:25 UTC, jakxnz commented
This is looking good to me! Just a couple things to address: There's console errors, and getting CircleCI to pass! Once those are done, let's merge it!

1. I can see a list of resorts ✅

![image](https://user-images.githubusercontent.com/1634995/169688210-06887d93-d0ea-40e9-ad50-12dd7b7fa674.png)


2. I can see resorts displayed in "pages" ✅

![image](https://user-images.githubusercontent.com/1634995/169688217-a676c3db-2fef-48ac-846d-da966babde5e.png)

3. I can change the current page of resorts ✅
4. When I revisit the URL of a specific page, I see that same page of resorts ✅
5. When I click a resort, I'm taken to that resorts booking page on their website ✅
6. When I click "Go to resort", I'm taking to the resort's page on our website ✅

![image](https://user-images.githubusercontent.com/1634995/169688277-ae14fca3-ae0d-4113-8a63-60498bff8dc3.png)


7. I can tell when something has gone wrong with resort fetching, without breaking my ability to navigate the website ✅
8. I can understand clearly where and how to filter the resorts I can see ✅

![image](https://user-images.githubusercontent.com/1634995/169688290-db9a7567-ac34-4630-a340-02cc3cf13b6d.png)

9. I see no errors on the resort page caused by Prop type failures 🔴

![image](https://user-images.githubusercontent.com/1634995/169688370-54c79d4e-e7b3-403d-a8f0-87dbc066fa2d.png)

2022-08-06 11:13 UTC, jakxnz approved these changes
9. I see no errors on the resort page caused by Prop type failures ✅ 

![](https://c.tenor.com/AueQOqqMU10AAAAC/iafcon-ice-and-fire-con.gif)

2022-08-06 11:15 UTC, merged