Filter Tray
underflip/shredindex-frontend pull request #49
Opened 2022-08-21 07:15 UTC by Krank3n

Added filter tray for upcoming filters
Added Lifestyle tray

2022-08-21 10:38 UTC, jakxnz requested changes
Very nice PR. The most thorough you've done yet! Great work considering the componentry, some state hanging, storybook, and cypress tests.

If you take a little longer now to make the state management a bit more mature, you'll save a bunch of headaches later.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +  const [visible, setVisible] = useState(showFilterTray);
Having multiple states that influence the tray visbility will cause concurrency headaches down the line. Visibility should be managed by one clean state, not multiple that we have to keep concurrent.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/LifeStyleTray/LifeStyleTray.js
> +  const [visible, setVisible] = useState(showLifeStyleTray);
Having multiple states that influence the tray visbility will cause concurrency headaches down the line. Visibility should be managed by one clean state, not multiple that we have to keep concurrent.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +        </CButton>
I reckon leave this out View button of the scope of this PR.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +          onClick={() => setVisible(false)}
Do we really need "clear all" to close the modal? Or just update the filters?

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +        </CButton>
I reckon leave this Clear all button out of the scope of this PR.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +        <CForm>
Can we make the filters themselves their own component? Wrapping them in a modal is kind of secondary importance to the filters themselves, so you'll find as the filters get more complex having them quite separate will be worthwhile.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +      <CModalBody>
I get a weird scrollbar aesthetic for the modal body. Do we need to style it across multiple browsers and devices?

2022-08-21 10:38 UTC, jakxnz commented on src/scss/components/_modal.scss
> +        background: $gray-600 var(--cui-btn-close-bg, url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='rgba%28255,255,255, 0.95%29'%3e%3cpath d='M.293.293a1
Should this be 10px by 10px (as according to the design)?

2022-08-21 10:38 UTC, jakxnz commented on cypress/integration/Filter/FilterTray.spec.js
> +describe('Filter Tray', () => {
Any chance you could create a few more specs as well (for other components you're adding)? Some of the components you're adding (that are very light right now) are gonna grow very quickly, and need decent file organisation.

Also, based on how much we'll be fine-tuning things down the line, we'll especially want automated tests on both the filters tray and the lifestyles tray, to make sure we don't unintentionally break them as we go along.

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +      />
How hard would it be to get these to fly up on mobile (and fly down when closed)?

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +  const [showLifeStyleTray, setShowLifeStyleTray] = useState(false);
Keeping the state in the controls feels a little backwards to be. Controls are dependents of the modal, not the other way around, yeah?

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +        onClick={() => setShowLifeStyleTray(!showLifeStyleTray)}
```suggestion
        onClick={() => setShowLifeStyleTray(true)}
```

Is there ever a scenario where this needs to be a two-way toggle?

2022-08-21 10:38 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +        onClick={() => setShowFilterTray(!showFilterTray)}
```suggestion
        onClick={() => setShowFilterTray(true)}
```

```suggestion
        onClick={() => setShowLifeStyleTray(true)}
```

Is there ever a scenario where this needs to be a two-way toggle?

2022-08-27 02:33 UTC, Krank3n commented on src/js/components/FilterMenu/FilterMenu.js
> +  const [showLifeStyleTray, setShowLifeStyleTray] = useState(false);
Hmmm I a bit confused with this. How would you go about setting the state within the modal without an external state for the button of opening it?

2022-08-27 02:35 UTC, Krank3n commented on src/js/components/FilterMenu/FilterMenu.js
> +      />
Im not sure what you mean by fly up and fly down?

2022-08-27 02:43 UTC, Krank3n commented on src/js/components/FilterMenu/FilterMenu.js
> +      />
Oh you mean the animation :D

2022-08-29 08:58 UTC, Krank3n commented on src/scss/_custom.scss
> +}
yep moved

2022-08-29 09:02 UTC, Krank3n commented on src/js/components/FilterTray/FilterTray.js
> +          onClick={() => setVisible(false)}
hmmm good point

2022-08-29 09:20 UTC, Krank3n commented on src/js/components/FilterTray/FilterTray.js
> +      <CModalBody>
Yea that needs to be done

2022-08-29 09:21 UTC, Krank3n commented on src/js/components/FilterTray/FilterTray.js
> +        <CForm>
Sure that makes sense

2022-08-29 09:35 UTC, Krank3n commented on src/scss/components/_modal.scss
> +        background: $gray-600 var(--cui-btn-close-bg, url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='rgba%28255,255,255, 0.95%29'%3e%3cpath d='M.293.293a1
the bounding box in the design confused me on this. Nice spotting dude

2022-08-29 10:04 UTC, Krank3n commented on src/js/components/FilterMenu/FilterMenu.js
> +      />
Hmmm this proved to be kinda hard. 

I couldn't seem to be able to apply this variable to mobile only using @media:

$modal-fade-transform:  translate(0, 50px);
https://coreui.io/react/docs/components/modal/

Do you have an idea how I can apply this to mobile only?

Also note, it looks horrible on desktop when it is applied.

2022-08-29 10:10 UTC, Krank3n commented on src/js/components/FilterMenu/FilterMenu.js
> +        aria-roledescription="show-filter-tray"
updated

2022-08-29 10:14 UTC, Krank3n commented on src/js/components/FilterTray/FilterTray.js
> +  const [visible, setVisible] = useState(showFilterTray);
DO you think this needs to be moved into global state with recoil?

2022-08-29 10:15 UTC, Krank3n commented on src/js/components/FilterTray/FilterTray.js
> +        </CButton>
taken out

2022-08-29 10:17 UTC, Krank3n commented on src/js/components/FilterMenu/FilterMenu.js
> +        onClick={() => setShowFilterTray(!showFilterTray)}
This confuses me a bit, does it not need to be set back to false in order to trigger true again?

2022-09-02 02:04 UTC, Krank3n commented on cypress/integration/Filter/FilterTray.spec.js
> +describe('Filter Tray', () => {
Not quite sure how detailed I should go here. But have added two more.

2022-11-02 07:34 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +  const [showLifeStyleTray, setShowLifeStyleTray] = useState(false);
Use state management

2022-12-13 01:35 UTC, Krank3n commented on src/js/components/FilterTray/FilterTray.js
> +      <CModalHeader onClose={() => { setVisible(false); handleClose(); }}>
@aurorekha @jakxnz Not sure, why I can't get this covered by tests. I thought this would manage to hit it. Any ideas?

`it('Should close filter tray when the modal header close button is hit', () => {
      if (cy.get('.filter-tray').should('not.exist')) {
        cy.get('.filter-menu__show-filters-tray').click().then(() => {
          cy.wait(100);
        });
        cy.get('.filter-tray').should('exist');
        cy.get('.filter-tray .modal-content .modal-header .btn-close').click().then(() => {
          cy.wait(100);
        });
        cy.get('.filter-tray').should('not.exist');`

2022-12-17 10:05 UTC, aurorekha approved these changes

2023-01-14 07:55 UTC, jakxnz requested changes
Nice improvements. Recoil makes state management much more intuitive. Just a few nitpicks from me, but I think this feature is more than good enough.

2023-01-14 07:55 UTC, jakxnz commented on src/scss/components/_forms.scss
> +}
Putting it in `scss/components/` confuses me a little, because there isn't a `forms` component in our codebase. My recommendation was something like ` scss/custom/partials/_forms.scss` because that indicates that it's just a partial, and it's a customisation of the underlying CoreUI styles (`custom/`) because our custom partial for customising CoreUI is `_custom.scss`.

One you have it setup in `scss/custom/partials/_forms.scss` you can then `@import` it into `_custom.scss` to avoid any guess work.

This seems like a bit of a nitpick, but if we ever want to split our CoreUI at a later time, or re-write our customisations, having them organised like this will make that way easier. It also makes it easier for different developers to avoid adding duplicate files/partials (because there is a pattern of how to recognise if someone has already customised in the areas you're customising).

2023-01-14 07:55 UTC, jakxnz commented on src/scss/_custom.scss
> +}
Can we apply the same organisation to this as my comment on `_forms.scss` e.g `custom/partials/_modal.scss`?

2023-01-14 07:55 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +import FilterTray, { showFilterTrayState } from '../FilterTray/FilterTray';
Nice, this is super intuitive.

2023-01-14 07:55 UTC, jakxnz commented on src/js/components/Filters/Filters.js
> +import {
I guarantee you, in the future when you have to make another set of Filters in another context you're gonna kick yourself for naming this as just generic "Filters" 😂. I've done it so many times. Maybe `RankedResortFilters`?

2023-01-14 07:55 UTC, jakxnz commented on src/scss/components/_modal.scss
> +        opacity: .7;
```suggestion
        opacity: 0.7;
```

2023-01-14 07:55 UTC, jakxnz commented on src/scss/components/_modal.scss
> +        padding: 2rem 2rem;
```suggestion
        padding: 2rem;
```

2023-01-14 07:55 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +      />
Must feel like the whole world is moving on desktop 😂. 

🤔 I hadn't noticed the element is being appended to the DOM on click. That always makes it harder to add animations/transitions. I had a quick play around and this seemed to do it:

```

@keyframes fly-up {
  from {
    top: 100%;
  }

  to {
    top: 0;
  }
}

.modal {
  animation: fly-up 0.2s ease-in-out;
}

@media (min-width: 576px) {
  .modal {
    animation: none;
  }
}
```

2023-01-14 07:55 UTC, jakxnz commented on src/js/components/FilterMenu/FilterMenu.js
> +        onClick={() => setShowFilterTray(!showFilterTray)}
It does, but it's more the question of whether this button needs to do it. As far as I can tell, this button only ever shows, and never hides.

2023-01-14 07:55 UTC, jakxnz commented on src/js/components/FilterTray/FilterTray.js
> +      <CModalHeader onClose={() => { setVisible(false); handleClose(); }}>
Nothing obvious comes to mind 🫠

2023-05-27 09:51 UTC, jakxnz approved these changes
Yeah boi.

2023-05-27 09:52 UTC, merged