Created FilterToggleButton component
underflip/shredindex-frontend pull request #56
Opened 2022-12-18 09:39 UTC by Krank3n

Created FilterToggleButton component
Added Story
Added Tests

2022-12-18 09:43 UTC, Krank3n commented
![FilterToggleButton](https://user-images.githubusercontent.com/45204791/208291436-6208aced-3e97-4c5a-8bf3-1ba40d7f4aef.gif)

2022-12-19 11:50 UTC, aurorekha commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +        onClick={() => showContainer()}
This is not a class function so can just leave it at onClick={showContainer}

2022-12-19 11:51 UTC, aurorekha commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +        onKeyPress={() => showContainer()}
and here {showContainer}

2022-12-19 11:53 UTC, aurorekha commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +                onKeyPress={() => hideContainer()}
both these functions too just call them without the parantheses.

2022-12-19 11:55 UTC, aurorekha reviewed
Requesting super small changes. The component looks ace and the gif definitely helped :)

2023-01-14 11:09 UTC, jakxnz requested changes
I love this feature.

I'm a little concerned about building features without a practical implementation, because without a practical implementation there may be obvious stuff missed or the feature might never get used at all if we change our minds. Is there a way to implement these with at least one real use of them in the app?

Really appreciate you leaving a video of the functionality in the PR comments.

2023-01-14 11:09 UTC, jakxnz commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +                  content={tooltip}
Does this happen to support markup? If not, everytime I've implemented tooltips, I've found it really limiting when they don't support markup as content.

2023-01-14 11:09 UTC, jakxnz commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +            {toggleOn
I notice a lot of `togglOn` conditions. Could there just be 2 components at a certain level, instead of always re-checking for the `toggleOn` condition?

2023-01-14 11:09 UTC, jakxnz commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +  const [toggleOn, setToggleOn] = useState(false);
If they refresh the page or re-open the filter stray, do we want people to be able to see the filters they have open? If so, will `useState` meet our needs? Or does this need more state management?

2023-01-14 11:09 UTC, jakxnz commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +  };
Not sure how helpful these are. Can't the onClick handlers just use the state mutator directly `onClick={setToggleOn(true)}`?

2023-01-14 11:09 UTC, jakxnz commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +    if (!toggleOn) {
What does the redundancy condition do? My assumption would be React won't re-render unless the value is different, so just using `setToggleOn(true)` even when it's already `true` might have the save effect as your redundancy check?

2023-01-14 11:09 UTC, jakxnz commented on src/scss/components/_filterToggleButton.scss
> +  transition-duration: .2s;
```suggestion
  animation-duration: 0.2s;
  transition-duration: 0.2s;
```

2023-01-26 00:40 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +        onClick={() => showContainer()}
Addressed

2023-01-26 00:40 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +        onKeyPress={() => showContainer()}
Addressed

2023-01-26 00:40 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +                onKeyPress={() => hideContainer()}
Addressed

2023-01-27 01:38 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +                  content={tooltip}
Its supports HTML

2023-01-27 05:39 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +  const [toggleOn, setToggleOn] = useState(false);
How about we use LocalStorage?

2023-01-27 05:59 UTC, Krank3n commented
> 



> I love this feature.
> 
> I'm a little concerned about building features without a practical implementation, because without a practical implementation there may be obvious stuff missed or the feature might never get used at all if we change our minds. Is there a way to implement these with at least one real use of them in the app?
> 
> Really appreciate you leaving a video of the functionality in the PR comments.

I think it would be best to get the FilterTray PR merged-in first so we can use it practically. What do you think?

2023-01-27 06:14 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +  const [toggleOn, setToggleOn] = useState(false);
I have updated it to use Local storage similar to the resort cards

2023-01-27 06:20 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +    if (!toggleOn) {
The close button is nested inside the header frame. and the whole structure is clickable for the toggleOn. So its only toggling on if it's not toggling false.

2023-01-27 06:40 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +            {toggleOn
Im not sure how much better I can make it... I may have to come back to this

2023-01-27 06:41 UTC, Krank3n commented on src/js/components/FilterToggleButton/FilterToggleButton.js
> +  };
I have taken these out

2023-01-27 06:42 UTC, Krank3n commented on src/scss/components/_filterToggleButton.scss
> +  transition-duration: .2s;
Updated. Another developer got me in the habit of removing all the zeros in intergers when I started at my first company.

2023-05-27 09:54 UTC, jakxnz commented
> I think it would be best to get the FilterTray PR merged-in first so we can use it practically. What do you think?

It's merged now 😃. Let us know when this branch is ready for its next PR 🤙🏻

2023-07-02 07:19 UTC, Krank3n commented
> I love this feature.
> 
> I'm a little concerned about building features without a practical implementation, because without a practical implementation there may be obvious stuff missed or the feature might never get used at all if we change our minds. Is there a way to implement these with at least one real use of them in the app?
> 
> Really appreciate you leaving a video of the functionality in the PR comments.

Hey Mate, I know we talked about this. But have forgotten the best approach. Should I continue with the double-range slider first, then try and implement this with it inside?

2023-11-26 22:07 UTC, jakxnz commented
> > I love this feature.
> > I'm a little concerned about building features without a practical implementation, because without a practical implementation there may be obvious stuff missed or the feature might never get used at all if we change our minds. Is there a way to implement these with at least one real use of them in the app?
> > Really appreciate you leaving a video of the functionality in the PR comments.
> 
> Hey Mate, I know we talked about this. But have forgotten the best approach. Should I continue with the double-range slider first, then try and implement this with it inside?

I've totally forgotten as well. My recommendation would be to make the nearest "cupcake". So that would be just a boolean filter that works to filter results.

2024-02-26 10:19 UTC, aurorekha approved these changes

2024-02-26 11:09 UTC, merged